"""Data shipped with the artifacts package: the artifact manifest.

``artifact_manifest.v1.json`` pins, per certified family, the upstream
repository, the frozen revision and the **per-file sha256** of every
file the runtime opens. It is generated by
``tools/generate_artifact_manifest.py`` from the campaign records and
cross-checked against ``tables/support_registry.json``; hand edits are
rejected by that tool's ``--check`` mode.

The file lives inside the package, not next to the repository's
generated tables, because the command line has to find it in an
installed wheel.
"""

from __future__ import annotations

from pathlib import Path

__all__ = [
    "ARTIFACT_CONVERSIONS",
    "ARTIFACT_MANIFEST",
    "SIBLING_ALIASES",
    "TABLE_DIR",
]

#: Directory of the shipped data files.
TABLE_DIR = Path(__file__).resolve().parent

#: The artifact manifest shipped with the package.
ARTIFACT_MANIFEST = TABLE_DIR / "artifact_manifest.v1.json"

#: Recipes for families whose artifact is derived from pinned upstream
#: inputs instead of downloaded whole. Kept as data because a family id
#: belongs in the routing tables, never in a module.
ARTIFACT_CONVERSIONS = TABLE_DIR / "artifact_conversions.v1.json"

#: Digest-protected mappings from audited model repositories to canonical
#: tokenizer artifacts.  Repository names are lookup hints; runtime admission
#: is based on the downloaded file's sha256.
SIBLING_ALIASES = TABLE_DIR / "sibling_aliases.v1.json"
