[package]
name = "toktier"
version.workspace = true

[dependencies]
toktier-routing-core = { path = "../toktier-routing-core", version = "=0.2.1" }
toktier-cuda-driver = { path = "../toktier-cuda-driver", version = "=0.2.1", optional = true }
toktier-store-core = { path = "../toktier-store-core", version = "=0.2.1" }
toktier-store-sqlite = { path = "../toktier-store-sqlite", version = "=0.2.1", optional = true }
