//! Single definition of the certification source-identity path sets.
//!
//! Both build scripts (`crates/toktier/build.rs` and
//! `crates/toktier-py/build.rs`) include this module with `#[path]`, so
//! the hashed path lists exist exactly once on the Rust side. The
//! tools-side transcription lives in `tools/source_identity_common.py`;
//! `tools/generate_registry.py --check` cross-checks the two against
//! each other and watches routing-core for unenrolled source files.
//!
//! A source identity is a bare SHA-256 over a domain tag plus
//! length-framed path/content pairs, in `PathBuf` component order.

use std::env;
use std::ffi::OsStr;
use std::fs;
use std::path::{Path, PathBuf};

use sha2::{Digest, Sha256};

pub const RUST_API_DOMAIN: &[u8] = b"toktier.rust_api.integrated_source.v1\0";
pub const FAST_CPU_DOMAIN: &[u8] = b"toktier.fast_cpu.integrated_source.v1\0";
pub const NATIVE_HOST_DOMAIN: &[u8] = b"toktier.prebuilt.native_host_source.v1\0";
pub const IDENTITY_SENTINEL_ENV: &str = "TOKTIER_IDENTITY_SENTINEL";
pub const IDENTITY_SENTINEL_HEX: &str = concat!(
    "73656e74696e656c",
    "73656e74696e656c",
    "73656e74696e656c",
    "73656e74696e656c",
);

pub fn identity_sentinel_enabled() -> bool {
    env::var_os(IDENTITY_SENTINEL_ENV).as_deref() == Some(OsStr::new("1"))
}

// ---------------------------------------------------------------------
// Resolved dependency closure.
// ---------------------------------------------------------------------
//
// In workspace mode the lockfile is one of the hashed files above, so
// the resolved graph is already part of every identity. A build from an
// unpacked registry copy cannot hash the sibling crates, replays the
// recorded digests instead, and would otherwise say nothing at all
// about how Cargo resolved this build's transitive versions. The
// helpers below let the build script compare the graph that governs
// this build against the graph that was judged, and report the answer.
// Since 0.2.6 the answer is reported in two places: the whole-closure
// reading, and the same comparison restricted to the certified core.
// `Registry::rust_api_build_certified` requires the second one to read
// `verified`; the first is reported and, for the periphery, carried as
// an advisory.

/// Explicit pointer to the lockfile that governs this build, for
/// layouts where it cannot be found by walking up from `OUT_DIR`.
pub const CARGO_LOCK_ENV: &str = "TOKTIER_CARGO_LOCK";

/// The judged lockfile as shipped inside the crate archive.
pub const JUDGED_LOCK_RELATIVE: &str = "data/build/judged_dependencies.lock";

/// The packages the judged build compiled, as shipped inside the crate
/// archive. Generated by `tools/generate_judged_closure.py`, which takes
/// them from Cargo's own account of that build.
pub const JUDGED_CLOSURE_RELATIVE: &str = "data/build/judged_compiled_closure.json";

/// The schema tag the judged compiled closure must carry.
pub const JUDGED_CLOSURE_SCHEMA: &str = "toktier.rust_compiled_closure.v2";

/// The package whose transitive closure is compared.
pub const CLOSURE_ROOT: &str = "toktier";

/// One `[[package]]` block of a Cargo lockfile.
pub struct LockPackage {
    pub name: String,
    pub version: String,
    pub source: Option<String>,
    pub checksum: Option<String>,
    pub dependencies: Vec<String>,
}

fn quoted_value(line: &str, key: &str) -> Option<String> {
    let rest = line.strip_prefix(key)?.trim_start();
    let rest = rest.strip_prefix('=')?.trim();
    let rest = rest.strip_prefix('"')?;
    rest.strip_suffix('"').map(str::to_owned)
}

/// Cargo lockfile format versions this reader understands.
///
/// The reader accepts the shape Cargo writes for these versions, in
/// which a package's `dependencies` is a multi-line array. A format
/// that wrote that array inline would parse into packages with no
/// dependencies at all, and an empty dependency list is exactly what a
/// leaf package looks like -- so the closure would quietly shrink to
/// the root, and a small enough judged side could still answer
/// `verified`. Naming the formats keeps that failure loud.
pub const SUPPORTED_LOCK_VERSIONS: &[u32] = &[3, 4];

/// The `version` key a Cargo lockfile declares before its first
/// `[[package]]` block, when it declares one.
pub fn lock_format_version(text: &str) -> Option<u32> {
    for line in text.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with('[') {
            break;
        }
        if let Some(rest) = trimmed.strip_prefix("version") {
            let rest = rest.trim_start().strip_prefix('=')?.trim();
            return rest.trim_matches('"').parse().ok();
        }
    }
    None
}

/// Refuse a lockfile this reader cannot claim to have read.
pub fn check_lock_format(label: &str, text: &str) -> Result<(), String> {
    match lock_format_version(text) {
        Some(version) if SUPPORTED_LOCK_VERSIONS.contains(&version) => Ok(()),
        Some(version) => Err(format!(
            "{label} declares lockfile format {version}; this build reads \
             {SUPPORTED_LOCK_VERSIONS:?}"
        )),
        None => Err(format!("{label} declares no lockfile format version")),
    }
}

/// Parse the `[[package]]` blocks of a Cargo lockfile.
///
/// Cargo writes this file, so the accepted shape is deliberately narrow:
/// only blocks introduced by `[[package]]` are read, which leaves
/// `[[patch.unused]]` and `[metadata]` out by construction. The shape is
/// tied to a declared format version by [`check_lock_format`], which
/// callers run first.
pub fn parse_lock(text: &str) -> Vec<LockPackage> {
    let mut packages = Vec::new();
    let mut current: Option<LockPackage> = None;
    let mut in_dependencies = false;
    for line in text.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with('[') {
            in_dependencies = false;
            if let Some(package) = current.take() {
                packages.push(package);
            }
            if trimmed == "[[package]]" {
                current = Some(LockPackage {
                    name: String::new(),
                    version: String::new(),
                    source: None,
                    checksum: None,
                    dependencies: Vec::new(),
                });
            }
            continue;
        }
        let Some(package) = current.as_mut() else {
            continue;
        };
        if in_dependencies {
            if trimmed.starts_with(']') {
                in_dependencies = false;
            } else if let Some(entry) = trimmed.strip_prefix('"') {
                if let Some(entry) = entry.split('"').next() {
                    package.dependencies.push(entry.to_owned());
                }
            }
            continue;
        }
        if trimmed.starts_with("dependencies") && trimmed.ends_with('[') {
            in_dependencies = true;
        } else if let Some(value) = quoted_value(trimmed, "name") {
            package.name = value;
        } else if let Some(value) = quoted_value(trimmed, "version") {
            package.version = value;
        } else if let Some(value) = quoted_value(trimmed, "source") {
            package.source = Some(value);
        } else if let Some(value) = quoted_value(trimmed, "checksum") {
            package.checksum = Some(value);
        }
    }
    if let Some(package) = current.take() {
        packages.push(package);
    }
    packages
}

fn resolve<'a>(packages: &'a [LockPackage], entry: &str) -> Vec<&'a LockPackage> {
    let mut fields = entry.split_whitespace();
    let name = fields.next().unwrap_or_default();
    let version = fields.next();
    // An entry without a version is unambiguous by Cargo's own rules;
    // taking every same-named package if one ever is not keeps the
    // comparison on the conservative side.
    packages
        .iter()
        .filter(|package| {
            package.name == name && version.is_none_or(|value| package.version == value)
        })
        .collect()
}

/// Every package reachable from `root`, itself included.
///
/// A lockfile's dependency lists are the union over features and
/// targets, so this is a superset of what any one build links: judging
/// too much rather than too little.
pub fn closure<'a>(packages: &'a [LockPackage], root: &str) -> Vec<&'a LockPackage> {
    let mut seen: Vec<&LockPackage> = Vec::new();
    let mut queue: Vec<&LockPackage> = packages
        .iter()
        .filter(|package| package.name == root)
        .collect();
    while let Some(package) = queue.pop() {
        if seen.iter().any(|found| std::ptr::eq(*found, package)) {
            continue;
        }
        seen.push(package);
        for entry in &package.dependencies {
            queue.extend(resolve(packages, entry));
        }
    }
    seen.sort_by(|left, right| {
        (&left.name, &left.version)
            .cmp(&(&right.name, &right.version))
            .then_with(|| left.checksum.cmp(&right.checksum))
    });
    seen
}

/// Which side of the certificate a package sits on.
///
/// `Core` is the default for anything a record does not classify: a
/// record this reader cannot place is treated as deciding the
/// certificate rather than as reportable, which is the fail-closed
/// direction.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Tier {
    /// TokTier's own crates, the packages they call directly, and the
    /// text-semantics libraries beneath them.
    Core,
    /// Everything else the judged build compiled.
    Periphery,
}

impl Tier {
    /// The tier a record names, or `Core` when it names none this reader
    /// knows.
    pub fn from_record(value: Option<&str>) -> Self {
        match value {
            Some("periphery") => Self::Periphery,
            _ => Self::Core,
        }
    }
}

/// One package the judged build compiled.
///
/// Names, versions and tiers: the content hash and origin of each one
/// come from the judged lockfile, so the two records cannot hold
/// different opinions about the same package.
///
/// A core package can also name the behaviour unit it belongs to -- the
/// Unicode tables a regex engine carries, the Oniguruma library a
/// binding links -- together with the version of that unit the evidence
/// was taken on and where it is read. Those are the packages whose
/// correct behaviour is defined by an evolving external standard, so
/// their package version moving is not by itself a change of behaviour.
/// The comparison of the unit itself happens at run time, in the binary
/// that links it; a package with no readable unit is compared exactly
/// here, which is the strict direction.
pub struct JudgedPackage {
    pub name: String,
    pub version: String,
    pub tier: Tier,
    pub behavior_unit: Option<String>,
    pub behavior_version: Option<String>,
    pub behavior_source: Option<String>,
}

impl JudgedPackage {
    /// Whether the version of this package's behaviour unit is one a
    /// running binary can read for itself.
    ///
    /// Everything else -- including a core package whose record names no
    /// unit, and one whose record is incomplete -- is compared exactly by
    /// the build script.
    pub fn behavior_is_probed(&self) -> bool {
        self.tier == Tier::Core
            && self.behavior_unit.is_some()
            && self.behavior_version.is_some()
            && self
                .behavior_source
                .as_deref()
                .is_some_and(|source| source != CRATE_VERSION_BEHAVIOR_SOURCE)
    }
}

/// The behaviour source a record names for a unit whose version is its
/// package version. Such a unit is compared exactly by the build script,
/// so no probe runs for it.
pub const CRATE_VERSION_BEHAVIOR_SOURCE: &str = "crate-version";

/// Separators for the one-line values the build script hands the runtime
/// through `cargo:rustc-env`. Both are ASCII separators, so neither can
/// appear in a package name, a version, or a rendered report.
pub const FIELD_SEPARATOR: char = '\u{1f}';
pub const RECORD_SEPARATOR: char = '\u{1e}';

/// One package the judged build compiled that this build does not.
///
/// Carried far enough to say what to do about it: which versions of the
/// same package this build reaches, whether the disagreement is about
/// the version at all, and which side of the certificate the package
/// sits on.
#[derive(Clone)]
pub struct Divergence {
    pub name: String,
    /// The version the certified build compiled.
    pub judged_version: String,
    /// Versions of this package this build's graph reaches, in closure
    /// order. Empty when this build reaches none.
    pub found_versions: Vec<String>,
    /// True when this build reaches the judged version, but as a
    /// different copy of it (content hash or origin).
    pub other_copy: bool,
    /// True when this build's graph holds more than one version of the
    /// package, so a Cargo package spec has to name the version too.
    pub ambiguous_spec: bool,
    /// Which side of the certificate the judged record puts this package
    /// on.
    pub tier: Tier,
    /// The behaviour unit this package belongs to, when the record names
    /// one whose version a running binary can read.
    pub behavior_unit: Option<String>,
}

impl Divergence {
    /// Whether this disagreement is about the version at all.
    ///
    /// A package that resolves from somewhere else, or that this build
    /// does not resolve, is not a version that moved: no probe of the
    /// behaviour it carries can speak for a copy that is not the judged
    /// one, so these stay with the exact comparison.
    fn is_version_move(&self) -> bool {
        !self.other_copy && !self.found_versions.is_empty()
    }

    /// The unit whose behaviour version answers for this package, when
    /// this is a version move of a package that names one.
    fn probed_unit(&self) -> Option<&str> {
        self.is_version_move()
            .then_some(self.behavior_unit.as_deref())
            .flatten()
    }

    /// Both sides of a version move, for the advisory.
    fn version_move(&self) -> String {
        format!(
            "{} {} -> {}",
            self.name,
            self.judged_version,
            self.found_versions.join(", ")
        )
    }
}

/// Cargo's compatibility range for a version: the leading non-zero
/// component and everything before it, so `1.4.2` and `1.4.0` share a
/// range while `0.3.34` and `0.4.0` do not.
fn compatibility_range(version: &str) -> String {
    let mut fields = version
        .split(['+', '-'])
        .next()
        .unwrap_or(version)
        .split('.');
    let mut range = Vec::new();
    for _ in 0..3 {
        let Some(field) = fields.next() else { break };
        range.push(field);
        if field != "0" {
            break;
        }
    }
    range.join(".")
}

impl Divergence {
    /// The version this build resolves that a `cargo update` can move
    /// onto the judged one: only a move inside one compatibility range
    /// can satisfy the requirements that already resolved, so this is the
    /// single reached version in the judged version's range.
    fn moveable_version(&self) -> Option<&str> {
        if self.other_copy {
            return None;
        }
        let range = compatibility_range(&self.judged_version);
        let mut compatible = self
            .found_versions
            .iter()
            .filter(|candidate| compatibility_range(candidate) == range);
        let first = compatible.next()?;
        compatible.next().is_none().then_some(first.as_str())
    }

    /// A command the reader can run as it stands, in the workspace that
    /// owns the governing lockfile.
    pub fn alignment_command(&self) -> Option<String> {
        let from = self.moveable_version()?;
        let specification = if self.ambiguous_spec {
            format!("{}@{}", self.name, from)
        } else {
            self.name.clone()
        };
        Some(format!(
            "cargo update --precise {} {specification}",
            self.judged_version
        ))
    }

    /// One sentence naming the disagreement.
    pub fn description(&self) -> String {
        let Self {
            name,
            judged_version,
            ..
        } = self;
        if self.other_copy {
            return format!(
                "{name} {judged_version} resolves here as a different copy of the judged package"
            );
        }
        if self.found_versions.is_empty() {
            return format!(
                "the judged build compiled {name} {judged_version}; this build resolves no {name}"
            );
        }
        format!(
            "the judged build compiled {name} {judged_version}; this build compiles {}",
            self.found_versions.join(", ")
        )
    }

    /// The same fact, compact enough to sit in a list of several.
    fn summary(&self) -> String {
        let Self {
            name,
            judged_version,
            ..
        } = self;
        if self.other_copy {
            return format!("{name} {judged_version} (a different copy of the judged package)");
        }
        if self.found_versions.is_empty() {
            return format!("{name} {judged_version} (not resolved here)");
        }
        format!(
            "{name} {judged_version} (this build compiles {})",
            self.found_versions.join(", ")
        )
    }
}

/// Every package the judged build compiled that this build does not,
/// in the judged closure's own order.
///
/// The direction is the point of the narrowing. Until 0.2.4 the question
/// was "is every package your lockfile reaches one we judged", and a
/// lockfile's dependency lists are the union over every feature and every
/// target -- so a Linux consumer was refused over a WebAssembly binding
/// that never entered the artifact. The question is now "is every package
/// our certified build compiled the one you compile", asked over the set
/// Cargo reported for that build.
///
/// What that deliberately stops asking is written down where readers of
/// the answer will find it (`docs/rust-api.md`).
pub fn closure_divergences<'a>(
    judged_lock: &'a [LockPackage],
    judged_closure: &[JudgedPackage],
    found: &'a [LockPackage],
) -> Result<Vec<Divergence>, String> {
    let judged_reference = closure(judged_lock, CLOSURE_ROOT);
    let found_closure = closure(found, CLOSURE_ROOT);
    if found_closure.is_empty() {
        return Err(format!(
            "no {CLOSURE_ROOT} package in the governing lockfile"
        ));
    }
    // This crate has dependencies in every configuration, so a root
    // with no edges is not a leaf -- it is what a lockfile shape this
    // reader cannot follow looks like from here. Answering from it
    // would compare the judged closure against the root alone.
    if found_closure
        .iter()
        .filter(|package| package.name == CLOSURE_ROOT)
        .all(|package| package.dependencies.is_empty())
    {
        return Err(format!(
            "the governing lockfile's {CLOSURE_ROOT} entry lists no dependencies"
        ));
    }
    if judged_closure.is_empty() {
        return Err("the judged compiled closure names no package".to_owned());
    }
    let mut divergences = Vec::new();
    let mut diverging_packages: Vec<Option<&LockPackage>> = Vec::new();
    for judged in judged_closure {
        // Where the content hash and origin of a judged package come
        // from. A compiled closure naming something the judged lockfile
        // does not hold is a broken record rather than a verdict about
        // this build, and it stops here rather than being answered.
        let reference = judged_reference
            .iter()
            .find(|package| package.name == judged.name && package.version == judged.version)
            .ok_or_else(|| {
                format!(
                    "the judged compiled closure names {} {}, which the judged lockfile does not \
                     hold",
                    judged.name, judged.version
                )
            })?;
        let same_name = found_closure
            .iter()
            .copied()
            .filter(|package| package.name == judged.name)
            .collect::<Vec<_>>();
        let exact = same_name
            .iter()
            .copied()
            .find(|package| package.version == judged.version);
        let same_copy = exact.is_some_and(|package| match &reference.checksum {
            // A registry package is judged by its content hash.
            Some(checksum) => package.checksum.as_deref() == Some(checksum.as_str()),
            // The judged graph holds this crate's own siblings as
            // workspace members, which carry no checksum. Their exact
            // versions are pinned by this crate's manifest, so the
            // origin is what is left to look at, and a git, alternate
            // registry, or replaced source is refused. A local path
            // copy carries no `source` key at all and is accepted:
            // that is also how a consumer building this workspace from
            // a checkout appears, so this rules out a relocated
            // origin rather than every `[patch]`.
            None => package
                .source
                .as_deref()
                .is_none_or(|source| source.starts_with("registry+")),
        });
        // Cargo unifies semver-compatible versions, so a compatible
        // sibling is the copy that compiles. The judged one also being
        // present somewhere in the graph does not change that.
        let competitor = same_name.iter().copied().find(|package| {
            package.version != judged.version
                && compatibility_range(&package.version) == compatibility_range(&judged.version)
        });
        if same_copy && competitor.is_none() {
            continue;
        }
        divergences.push(Divergence {
            name: judged.name.clone(),
            judged_version: judged.version.clone(),
            found_versions: same_name
                .iter()
                .map(|package| package.version.clone())
                .collect(),
            other_copy: exact.is_some() && !same_copy,
            ambiguous_spec: same_name.len() > 1,
            tier: judged.tier,
            behavior_unit: judged
                .behavior_is_probed()
                .then(|| judged.behavior_unit.clone())
                .flatten(),
        });
        diverging_packages.push(competitor.or(exact));
    }
    Ok(order_for_update(divergences, &diverging_packages))
}

/// The same divergences, in an order Cargo can carry out.
///
/// Cargo moves a package only to a version its dependents still accept,
/// so a package that another diverging package depends on has to wait
/// for that dependent to move first. Listing them in that order is what
/// makes the commands runnable one after another; ties keep the
/// closure's own order, and a dependency cycle -- which a lockfile
/// can hold through dev-dependencies -- falls back to it as well.
fn order_for_update(
    divergences: Vec<Divergence>,
    packages: &[Option<&LockPackage>],
) -> Vec<Divergence> {
    let depends_on = |package: Option<&LockPackage>, index: usize| {
        package.is_some_and(|package| {
            package.dependencies.iter().any(|entry| {
                entry.split_whitespace().next() == Some(divergences[index].name.as_str())
            })
        })
    };
    let mut waiting = (0..divergences.len())
        .map(|index| {
            (0..divergences.len())
                .filter(|other| *other != index && depends_on(packages[*other], index))
                .count()
        })
        .collect::<Vec<_>>();
    let mut placed = vec![false; divergences.len()];
    let mut order = Vec::with_capacity(divergences.len());
    while order.len() < divergences.len() {
        let next = (0..divergences.len())
            .find(|index| !placed[*index] && waiting[*index] == 0)
            .or_else(|| (0..divergences.len()).find(|index| !placed[*index]))
            .expect("an unplaced package");
        placed[next] = true;
        order.push(next);
        for dependency in packages[next].iter().flat_map(|p| p.dependencies.iter()) {
            let name = dependency.split_whitespace().next();
            for index in 0..divergences.len() {
                if !placed[index] && Some(divergences[index].name.as_str()) == name {
                    waiting[index] = waiting[index].saturating_sub(1);
                }
            }
        }
    }
    let mut divergences = divergences.into_iter().map(Some).collect::<Vec<_>>();
    order
        .into_iter()
        .map(|index| divergences[index].take().expect("one place each"))
        .collect()
}

/// The divergences written out as a report the reader can act on.
pub fn render_divergences(divergences: &[Divergence]) -> String {
    let mut report = match divergences {
        [single] => single.description(),
        many => format!(
            "{} packages this build compiles are not the judged ones: {}",
            many.len(),
            many.iter()
                .map(Divergence::summary)
                .collect::<Vec<_>>()
                .join("; ")
        ),
    };
    let commands = divergences
        .iter()
        .filter_map(Divergence::alignment_command)
        .collect::<Vec<_>>();
    if !commands.is_empty() {
        report.push_str(&format!(
            ". To align this build, run in the workspace that owns the governing lockfile: {}",
            commands.join(" && ")
        ));
    }
    report.push_str(&render_tail(divergences));
    report
}

/// The same packages, said as an advisory rather than as a refusal.
///
/// The list and the commands are the ones the whole-closure report
/// carries; what changes is the frame around them. These packages are
/// outside the certified core, so the sentence says where they are, that
/// they are reported rather than gating, and how to align them anyway --
/// without calling them harmless, which is not what is being claimed.
pub fn render_advisory(divergences: &[Divergence]) -> String {
    let mut report = match divergences {
        [single] => format!(
            "one package outside the certified core is not the judged one; it is reported here \
             and does not enter the certificate: {}",
            single.summary()
        ),
        many => format!(
            "{} packages outside the certified core are not the judged ones; they are reported \
             here and do not enter the certificate: {}",
            many.len(),
            many.iter()
                .map(Divergence::summary)
                .collect::<Vec<_>>()
                .join("; ")
        ),
    };
    let commands = divergences
        .iter()
        .filter_map(Divergence::alignment_command)
        .collect::<Vec<_>>();
    if !commands.is_empty() {
        report.push_str(&format!(
            ". To align them anyway, run in the workspace that owns the governing lockfile: {}",
            commands.join(" && ")
        ));
    }
    report.push_str(&render_tail(divergences));
    report
}

/// The clauses both reports end with: what a version change cannot
/// align, and what this build compiles that the judged one did not.
fn render_tail(divergences: &[Divergence]) -> String {
    let mut report = String::new();
    let by_copy = divergences
        .iter()
        .filter(|divergence| divergence.other_copy)
        .map(|divergence| divergence.name.as_str())
        .collect::<Vec<_>>();
    if !by_copy.is_empty() {
        report.push_str(&format!(
            ". {} resolves from somewhere other than the judged package, so a version change does \
             not align it: it comes back to the judged copy when the [patch] or source replacement \
             redirecting it is removed",
            by_copy.join(", ")
        ));
    }
    let without_command = divergences
        .iter()
        .filter(|divergence| !divergence.other_copy && divergence.alignment_command().is_none())
        .map(|divergence| divergence.name.as_str())
        .collect::<Vec<_>>();
    if !without_command.is_empty() {
        report.push_str(&format!(
            ". No version this build resolves is compatible with the judged one for {}, so this \
             build compiles something the judged one did not: matching the judged feature and \
             target selection is what brings it back",
            without_command.join(", ")
        ));
    }
    report
}

/// Whether every package the judged build compiled is the one this build
/// compiles.
pub fn compare_closures(
    judged_lock: &[LockPackage],
    judged_closure: &[JudgedPackage],
    found: &[LockPackage],
) -> Result<(), String> {
    let divergences = closure_divergences(judged_lock, judged_closure, found)?;
    if divergences.is_empty() {
        return Ok(());
    }
    Err(render_divergences(&divergences))
}

/// How this crate is being consumed.
///
/// The two forms differ in what the files beside the manifest mean. In a
/// workspace the lockfile next to these sources is a real lockfile of a
/// real build, and `data/build/judged_dependencies.lock` is a byte copy
/// of it, so naming either one names this build's own graph. An unpacked
/// registry copy carries those same records as a *record of the build
/// that was judged*, taken on another machine on another day; they say
/// nothing about the build now running.
#[derive(Clone, Copy)]
pub enum Consumption<'a> {
    /// Built from its own workspace, or as a path or `[patch]`
    /// dependency of a larger one. Carries the manifest directory, whose
    /// ancestors are searched as well.
    Workspace(&'a Path),
    /// Built from an unpacked registry copy. Carries the manifest
    /// directory, which is where the judged records travel.
    Packaged(&'a Path),
}

/// The outcome of looking for the lockfile that governs this build.
pub enum GoverningLock {
    /// A lockfile that can speak for this build.
    Found(PathBuf),
    /// `TOKTIER_CARGO_LOCK` named this package's own record of the judged
    /// build. That record describes another build, so it is answered
    /// rather than compared.
    JudgedRecordNamed(PathBuf),
    /// No lockfile that could govern this build was named or found.
    Missing,
}

/// Whether a named path is this package's own record of the judged
/// build rather than a lockfile describing this one.
///
/// Two signals, either of which is enough:
///
/// - the path resolves inside the package's own `data/` directory, which
///   is where the judged records travel and holds nothing that governs a
///   build (resolving both sides first, so a path dressed up with `..`
///   or a symlink is read the same way as a plain one);
/// - the named file is byte for byte the packaged judged lockfile, which
///   covers a copy of it placed somewhere else.
///
/// A real consumer's lockfile can trip neither. It lives in that
/// consumer's own workspace, and it cannot have the judged file's bytes:
/// the judged lockfile is the source workspace's own, where `toktier`
/// and its siblings are workspace members carrying no `source` and no
/// `checksum`, while any consumer's lockfile holds the consumer's own
/// package and reaches `toktier` from a registry.
fn names_the_judged_record(named: &Path, manifest_dir: &Path) -> bool {
    let data = manifest_dir.join("data");
    let resolved_named = fs::canonicalize(named).unwrap_or_else(|_| named.to_owned());
    let resolved_data = fs::canonicalize(&data).unwrap_or(data);
    if resolved_named.starts_with(&resolved_data) {
        return true;
    }
    let judged = manifest_dir.join(JUDGED_LOCK_RELATIVE);
    match (fs::read(named), fs::read(&judged)) {
        (Ok(named), Ok(judged)) => named == judged,
        _ => false,
    }
}

/// The lockfile that governs this build, if it can be named.
///
/// `OUT_DIR` sits inside the target directory of the build that is
/// consuming this crate, so its ancestors reach that build's workspace
/// root. The unpacked crate's own directory is searched only in
/// workspace mode: a registry copy ships the lockfile recorded at
/// publication time, and comparing that against itself would answer
/// nothing.
pub fn locate_governing_lock(out_dir: &Path, consumption: Consumption<'_>) -> GoverningLock {
    locate_governing_lock_from(
        env::var_os(CARGO_LOCK_ENV).map(PathBuf::from),
        out_dir,
        consumption,
    )
}

/// The same search with the environment already read, so the rules can
/// be exercised without a process-wide variable.
fn locate_governing_lock_from(
    explicit: Option<PathBuf>,
    out_dir: &Path,
    consumption: Consumption<'_>,
) -> GoverningLock {
    if let Some(path) = explicit {
        if !path.is_file() {
            return GoverningLock::Missing;
        }
        // Only a packaged build can be handed its own judged record: in a
        // workspace that record is a byte copy of the lockfile that
        // really does govern the build, so naming it is naming the right
        // file by another name.
        if let Consumption::Packaged(manifest) = consumption {
            if names_the_judged_record(&path, manifest) {
                return GoverningLock::JudgedRecordNamed(path);
            }
        }
        return GoverningLock::Found(path);
    }
    let manifest = match consumption {
        Consumption::Workspace(manifest) => Some(manifest),
        Consumption::Packaged(_) => None,
    };
    for root in [Some(out_dir), manifest].into_iter().flatten() {
        for ancestor in root.ancestors() {
            let candidate = ancestor.join("Cargo.lock");
            if candidate.is_file() {
                return GoverningLock::Found(candidate);
            }
        }
    }
    GoverningLock::Missing
}

/// What to say when no lockfile governing this build could be named.
///
/// The pointer to the packaged copy is there to be read, not to be
/// handed back as the governing lockfile: the comparison believes the
/// file it is given, so naming one that does not govern this build moves
/// the comparison rather than aligning the build.
pub fn unlocated_status() -> String {
    format!(
        "unlocated: no lockfile governing this build was found above OUT_DIR, so the resolved \
         graph could not be compared and this build is not certified. The judged graph travels \
         with the crate as {JUDGED_LOCK_RELATIVE}, and the packages the judged build actually \
         compiled as {JUDGED_CLOSURE_RELATIVE}; both can be read there. Building from a \
         workspace whose own Cargo.lock resolves those versions is what earns `verified`, for the \
         certified core and for the whole closure alike; {CARGO_LOCK_ENV} names the governing \
         lockfile for layouts where walking up from OUT_DIR does not reach it, and is compared \
         as given"
    )
}

/// What to say when `TOKTIER_CARGO_LOCK` names this package's own record
/// of the judged build.
///
/// The record is a true account of another build. Read against this one
/// it would compare a file with itself and agree every time, so this
/// build is left uncertified and the two routes that do reach `verified`
/// are named instead.
pub fn judged_record_named_status(named: &Path) -> String {
    format!(
        "unlocated: {CARGO_LOCK_ENV} names {}, which is this package's own record of the judged \
         build ({JUDGED_LOCK_RELATIVE}) rather than a lockfile describing this one, so there is \
         nothing here to compare this build against and this build is not certified. Two routes \
         do reach `verified`: align this build's own lockfile with the judged versions and let \
         {CARGO_LOCK_ENV} name that file -- or leave the variable unset, so the lockfile above \
         OUT_DIR is used -- or build inside a workspace that already holds the judged graph",
        named.display()
    )
}

/// What one comparison of this build against the judged one produced.
///
/// Kept apart from the sentences it turns into, because the same reading
/// answers several questions: the whole closure, the certified core, the
/// packages whose behaviour the runtime probes for itself, and the
/// advisory for everything else.
enum Comparison {
    /// The comparison could not be made and the reason is a mismatch.
    Refused(String),
    /// No lockfile that governs this build could be named.
    Unlocated(String),
    /// The comparison ran; these packages disagree.
    Compared(Vec<Divergence>),
}

fn compare_for_status(
    judged_lock: &Path,
    judged_closure: &Result<Vec<JudgedPackage>, String>,
    governing: &GoverningLock,
) -> Comparison {
    let judged_closure = match judged_closure {
        Ok(packages) => packages,
        Err(reason) => return Comparison::Refused(reason.clone()),
    };
    let governing = match governing {
        GoverningLock::Found(path) => path,
        GoverningLock::JudgedRecordNamed(path) => {
            return Comparison::Unlocated(judged_record_named_status(path))
        }
        GoverningLock::Missing => return Comparison::Unlocated(unlocated_status()),
    };
    let judged = match fs::read_to_string(judged_lock) {
        Ok(text) => match check_lock_format("the judged lockfile", &text) {
            Ok(()) => parse_lock(&text),
            Err(reason) => return Comparison::Refused(reason),
        },
        Err(error) => {
            return Comparison::Refused(format!("judged lockfile is unreadable: {error}"))
        }
    };
    let found = match fs::read_to_string(governing) {
        Ok(text) => match check_lock_format("the governing lockfile", &text) {
            Ok(()) => parse_lock(&text),
            Err(reason) => return Comparison::Refused(reason),
        },
        Err(error) => {
            return Comparison::Refused(format!("governing lockfile is unreadable: {error}"))
        }
    };
    match closure_divergences(&judged, judged_closure, &found) {
        Ok(divergences) => Comparison::Compared(divergences),
        Err(reason) => Comparison::Refused(reason),
    }
}

/// The three-way answer for one subset of the comparison.
fn status_for(comparison: &Comparison, selected: Vec<&Divergence>) -> String {
    match comparison {
        Comparison::Refused(reason) => format!("mismatched: {reason}"),
        Comparison::Unlocated(reason) => reason.clone(),
        Comparison::Compared(_) if selected.is_empty() => "verified".to_owned(),
        Comparison::Compared(_) => format!("mismatched: {}", render_selected(&selected)),
    }
}

/// One line naming how this build's resolved graph compares with the
/// judged one: `verified`, `unlocated: <guidance>`, or
/// `mismatched: <what differs, and what aligns it>`.
///
/// This is the whole-closure reading, unchanged in name, type and shape
/// since 0.2.4. Since 0.2.6 it is reported rather than gating;
/// [`ClosureStatuses::core_static`] is the reading the certificate uses.
///
/// Every way of not knowing is a `mismatched` or `unlocated` line, never
/// a `verified` one and never a panic: an unreadable record is a reason
/// to withhold certification, not a reason to fail someone's build.
pub fn dependency_closure_status(
    judged_lock: &Path,
    judged_closure: &Result<Vec<JudgedPackage>, String>,
    governing: &GoverningLock,
) -> String {
    let comparison = compare_for_status(judged_lock, judged_closure, governing);
    let selected = match &comparison {
        Comparison::Compared(divergences) => divergences.iter().collect(),
        _ => Vec::new(),
    };
    status_for(&comparison, selected)
}

/// Every answer the build script hands the compiled crate, taken from
/// one reading of the two lockfiles.
pub struct ClosureStatuses {
    /// The whole compiled closure, in the shape 0.2.4 introduced.
    pub strict: String,
    /// The same comparison restricted to the packages the certificate
    /// speaks for, less those whose behaviour version the running binary
    /// reads for itself.
    pub core_static: String,
    /// The core packages whose package version moved and whose behaviour
    /// version the running binary reads: one `unit<RS>report` record per
    /// unit, separated by `FIELD_SEPARATOR`. Empty when none moved.
    pub r2_drift: String,
    /// The packages outside the certified core that differ, as a report
    /// with the commands that align them. Empty when none differ.
    pub advisory: String,
    /// The behaviour version the evidence was taken on, per unit:
    /// `unit<RS>version<RS>source` records separated by
    /// `FIELD_SEPARATOR`.
    pub judged_behavior: String,
}

/// Which behaviour units the record describes consistently.
///
/// A unit two records disagree about is left out, which puts every
/// package of it back on the exact comparison.
fn probed_units(judged_closure: &[JudgedPackage]) -> Vec<(String, String, String)> {
    let mut units: Vec<(String, String, String)> = Vec::new();
    let mut poisoned: Vec<String> = Vec::new();
    for package in judged_closure {
        if !package.behavior_is_probed() {
            continue;
        }
        let unit = package.behavior_unit.clone().expect("a probed unit");
        let version = package.behavior_version.clone().expect("a probed version");
        let source = package.behavior_source.clone().expect("a probed source");
        match units.iter().find(|(name, _, _)| *name == unit) {
            Some((_, recorded, recorded_source))
                if recorded == &version && recorded_source == &source => {}
            Some(_) => {
                if !poisoned.contains(&unit) {
                    poisoned.push(unit);
                }
            }
            None => units.push((unit, version, source)),
        }
    }
    units.retain(|(name, _, _)| !poisoned.contains(name));
    units.sort();
    units
}

/// Whether a divergence is one the runtime's own probe answers for.
fn is_probed_move(divergence: &Divergence, units: &[(String, String, String)]) -> bool {
    divergence
        .probed_unit()
        .is_some_and(|unit| units.iter().any(|(name, _, _)| name == unit))
}

/// The divergences of one subset, rendered with their commands.
fn render_selected(selected: &[&Divergence]) -> String {
    let owned = selected
        .iter()
        .map(|divergence| (*divergence).clone())
        .collect::<Vec<_>>();
    render_divergences(&owned)
}

/// Every answer the build script emits, from one comparison.
pub fn closure_statuses(
    judged_lock: &Path,
    judged_closure: &Result<Vec<JudgedPackage>, String>,
    governing: &GoverningLock,
) -> ClosureStatuses {
    let comparison = compare_for_status(judged_lock, judged_closure, governing);
    let units = match judged_closure {
        Ok(packages) => probed_units(packages),
        Err(_) => Vec::new(),
    };
    let judged_behavior = units
        .iter()
        .map(|(unit, version, source)| {
            format!("{unit}{RECORD_SEPARATOR}{version}{RECORD_SEPARATOR}{source}")
        })
        .collect::<Vec<_>>()
        .join(&FIELD_SEPARATOR.to_string());
    let empty: Vec<Divergence> = Vec::new();
    let divergences = match &comparison {
        Comparison::Compared(divergences) => divergences.as_slice(),
        _ => empty.as_slice(),
    };
    let strict = status_for(&comparison, divergences.iter().collect());
    let core_static = status_for(
        &comparison,
        divergences
            .iter()
            .filter(|divergence| {
                divergence.tier == Tier::Core && !is_probed_move(divergence, &units)
            })
            .collect(),
    );
    let mut drift = Vec::new();
    for (unit, _, _) in &units {
        let moved = divergences
            .iter()
            .filter(|divergence| {
                is_probed_move(divergence, &units)
                    && divergence.probed_unit() == Some(unit.as_str())
            })
            .map(Divergence::version_move)
            .collect::<Vec<_>>();
        if !moved.is_empty() {
            drift.push(format!("{unit}{RECORD_SEPARATOR}{}", moved.join("; ")));
        }
    }
    let advisory = match &comparison {
        Comparison::Compared(_) => {
            let outside = divergences
                .iter()
                .filter(|divergence| divergence.tier == Tier::Periphery)
                .collect::<Vec<_>>();
            if outside.is_empty() {
                String::new()
            } else {
                render_advisory(
                    &outside
                        .iter()
                        .map(|divergence| (*divergence).clone())
                        .collect::<Vec<_>>(),
                )
            }
        }
        // A build that could not be compared has nothing to advise
        // about: the core answer already says so.
        _ => String::new(),
    };
    ClosureStatuses {
        strict,
        core_static,
        r2_drift: drift.join(&FIELD_SEPARATOR.to_string()),
        advisory,
        judged_behavior,
    }
}

fn collect_tree(root: &Path, path: &Path, output: &mut Vec<PathBuf>) {
    let mut entries = fs::read_dir(path)
        .unwrap_or_else(|error| panic!("cannot read {}: {error}", path.display()))
        .map(|entry| entry.expect("source directory entry").path())
        .collect::<Vec<_>>();
    entries.sort();
    for entry in entries {
        if entry.is_dir() {
            collect_tree(root, &entry, output);
        } else if entry.is_file() {
            output.push(entry.strip_prefix(root).expect("workspace path").to_owned());
        }
    }
}

fn paths_from(root: &Path, files: &[&str], trees: &[&str]) -> Vec<PathBuf> {
    let mut paths = files.iter().map(PathBuf::from).collect::<Vec<_>>();
    for tree in trees {
        collect_tree(root, &root.join(tree), &mut paths);
    }
    paths.sort();
    paths.dedup();
    paths
}

pub fn fast_cpu_source_paths(root: &Path) -> Vec<PathBuf> {
    paths_from(
        root,
        &[
            "Cargo.lock",
            "Cargo.toml",
            "pyproject.toml",
            "rust-toolchain.toml",
            "crates/toktier/build_support/source_identity.rs",
            "crates/toktier-routing-core/Cargo.toml",
            "crates/toktier-routing-core/src/fast_cpu.rs",
            "crates/toktier-routing-core/src/lib.rs",
            "crates/toktier-routing-core/src/reference.rs",
            "crates/toktier-routing-core/src/runtime.rs",
            "crates/toktier-store-core/Cargo.toml",
            "crates/toktier-py/Cargo.toml",
            "crates/toktier-py/build.rs",
            "crates/toktier-py/src/lib.rs",
            "src/toktier/backends/fast_cpu.py",
            "src/toktier/repair/tables/fast_repair_families.v1.json",
            "src/toktier/repair/tables/repair_pclass.v1.zlib",
        ],
        &[
            "crates/toktier-gigatoken-core",
            "crates/toktier-store-core/src",
        ],
    )
}

pub fn native_host_source_paths(root: &Path) -> Vec<PathBuf> {
    paths_from(
        root,
        &[
            "Cargo.lock",
            "Cargo.toml",
            "pyproject.toml",
            "rust-toolchain.toml",
            "crates/toktier/build_support/source_identity.rs",
            "crates/toktier-py/Cargo.toml",
            "crates/toktier-py/build.rs",
            "crates/toktier-py/src/lib.rs",
            "src/toktier/engine/gpu/native.py",
            "src/toktier/kernels/bpe_tables.py",
        ],
        &[
            "crates/toktier-cuda-driver",
            "crates/toktier-routing-core",
            "crates/toktier-store-core",
            "crates/toktier-store-sqlite",
        ],
    )
}

pub fn rust_api_source_paths(root: &Path) -> Vec<PathBuf> {
    paths_from(
        root,
        &[
            "Cargo.lock",
            "Cargo.toml",
            "rust-toolchain.toml",
            "crates/toktier/Cargo.toml",
            "crates/toktier/build.rs",
            "crates/toktier/build_support/source_identity.rs",
            "src/toktier/repair/tables/fast_repair_families.v1.json",
            "src/toktier/repair/tables/repair_pclass.v1.zlib",
        ],
        &[
            "crates/toktier/src",
            "crates/toktier-cuda-driver",
            "crates/toktier-gigatoken-core",
            "crates/toktier-routing-core",
            "crates/toktier-store-core",
            "crates/toktier-store-sqlite",
        ],
    )
}

pub fn source_digest(root: &Path, domain: &[u8], paths: &[PathBuf]) -> String {
    let mut digest = Sha256::new();
    digest.update(domain);
    for relative in paths {
        let rendered = relative
            .to_string_lossy()
            .replace(std::path::MAIN_SEPARATOR, "/");
        let path = rendered.as_bytes();
        let content = fs::read(root.join(relative))
            .unwrap_or_else(|error| panic!("cannot read {rendered}: {error}"));
        digest.update((path.len() as u64).to_le_bytes());
        digest.update(path);
        digest.update((content.len() as u64).to_le_bytes());
        digest.update(content);
    }
    hex(digest.finalize().as_slice())
}

pub fn hex(bytes: &[u8]) -> String {
    bytes.iter().map(|byte| format!("{byte:02x}")).collect()
}

#[cfg(test)]
mod tests {
    use std::fs;
    use std::path::{Path, PathBuf};

    use super::{
        check_lock_format, closure, closure_statuses, compare_closures, dependency_closure_status,
        locate_governing_lock_from, lock_format_version, parse_lock, ClosureStatuses, Consumption,
        GoverningLock, JudgedPackage, Tier, CARGO_LOCK_ENV, CRATE_VERSION_BEHAVIOR_SOURCE,
        JUDGED_CLOSURE_RELATIVE, JUDGED_LOCK_RELATIVE, RECORD_SEPARATOR, SUPPORTED_LOCK_VERSIONS,
    };

    const JUDGED: &str = r#"
version = 4

[[package]]
name = "toktier"
version = "0.2.4"
dependencies = [
 "serde",
 "tempfile",
 "toktier-routing-core",
]

[[package]]
name = "serde"
version = "1.0.228"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "aaaa"
dependencies = [
 "memchr",
]

[[package]]
name = "memchr"
version = "2.8.3"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "bbbb"

[[package]]
name = "tempfile"
version = "3.23.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "cccc"

[[package]]
name = "toktier-routing-core"
version = "0.2.4"

[[package]]
name = "unrelated"
version = "9.9.9"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "dddd"

[[patch.unused]]
name = "serde"
version = "1.0.999"
"#;

    /// A consumer's lockfile: no dev-dependency of the root, and the
    /// sibling crate arrives from the registry rather than as a
    /// workspace member.
    const CONSUMER: &str = r#"
version = 4

[[package]]
name = "toktier"
version = "0.2.4"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "eeee"
dependencies = [
 "serde",
 "toktier-routing-core",
]

[[package]]
name = "serde"
version = "1.0.228"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "aaaa"
dependencies = [
 "memchr 2.8.3",
]

[[package]]
name = "memchr"
version = "2.8.3"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "bbbb"

[[package]]
name = "toktier-routing-core"
version = "0.2.4"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "ffff"
"#;

    /// What Cargo compiles for the judged build of the fixture above:
    /// the root, its two normal dependencies, and what they reach. The
    /// root's `tempfile` is a development dependency and is deliberately
    /// not here -- that absence is the narrowing this release makes.
    fn compiled() -> Vec<JudgedPackage> {
        [
            ("toktier", "0.2.4"),
            ("serde", "1.0.228"),
            ("memchr", "2.8.3"),
            ("toktier-routing-core", "0.2.4"),
        ]
        .into_iter()
        .map(|(name, version)| core_package(name, version))
        .collect()
    }

    /// One judged package of the certified core, with no behaviour unit
    /// of its own: the shape of an R0 or R1 entry.
    fn core_package(name: &str, version: &str) -> JudgedPackage {
        JudgedPackage {
            name: name.to_owned(),
            version: version.to_owned(),
            tier: Tier::Core,
            behavior_unit: None,
            behavior_version: None,
            behavior_source: None,
        }
    }

    /// The same package outside the certified core.
    fn periphery_package(name: &str, version: &str) -> JudgedPackage {
        JudgedPackage {
            tier: Tier::Periphery,
            ..core_package(name, version)
        }
    }

    /// A core package whose behaviour version a running binary reads.
    fn probed_package(name: &str, version: &str, unit: &str) -> JudgedPackage {
        JudgedPackage {
            behavior_unit: Some(unit.to_owned()),
            behavior_version: Some("16.0".to_owned()),
            behavior_source: Some("probe:regex-age".to_owned()),
            ..core_package(name, version)
        }
    }

    fn statuses(judged_closure: Vec<JudgedPackage>, found: &str) -> ClosureStatuses {
        let temporary = tempfile::tempdir().unwrap();
        let judged_lock = temporary.path().join("judged.lock");
        let governing = temporary.path().join("Cargo.lock");
        fs::write(&judged_lock, JUDGED).unwrap();
        fs::write(&governing, found).unwrap();
        closure_statuses(
            &judged_lock,
            &Ok(judged_closure),
            &GoverningLock::Found(governing),
        )
    }

    /// A consumer graph in which `memchr` moved and nothing else did.
    fn memchr_moved() -> String {
        CONSUMER
            .replace("memchr 2.8.3", "memchr 2.8.4")
            .replace("version = \"2.8.3\"", "version = \"2.8.4\"")
    }

    fn compare(judged_lock: &str, found: &str) -> Result<(), String> {
        compare_closures(&parse_lock(judged_lock), &compiled(), &parse_lock(found))
    }

    #[test]
    fn parsing_reads_packages_and_skips_other_blocks() {
        let packages = parse_lock(JUDGED);
        assert_eq!(packages.len(), 6);
        let serde = packages
            .iter()
            .find(|package| package.name == "serde")
            .unwrap();
        assert_eq!(serde.version, "1.0.228");
        assert_eq!(serde.checksum.as_deref(), Some("aaaa"));
        assert_eq!(serde.dependencies, vec!["memchr".to_owned()]);
        // The unused patch entry is not a package.
        assert!(packages.iter().all(|package| package.version != "1.0.999"));
    }

    #[test]
    fn the_closure_is_what_the_root_reaches() {
        let packages = parse_lock(JUDGED);
        let names = closure(&packages, "toktier")
            .into_iter()
            .map(|package| package.name.as_str())
            .collect::<Vec<_>>();
        assert_eq!(
            names,
            vec![
                "memchr",
                "serde",
                "tempfile",
                "toktier",
                "toktier-routing-core"
            ]
        );
    }

    #[test]
    fn a_matching_consumer_graph_is_accepted() {
        assert_eq!(compare(JUDGED, CONSUMER), Ok(()));
    }

    /// The narrowing itself. The judged lockfile reaches `tempfile`, a
    /// development dependency of the root that no consumer builds, so a
    /// consumer resolving a different one used to be refused over a
    /// package that never entered the artifact. It no longer is.
    #[test]
    fn a_package_the_judged_build_never_compiled_is_not_judged() {
        let with_other_tempfile = CONSUMER.replace(
            "dependencies = [\n \"serde\",\n \"toktier-routing-core\",",
            "dependencies = [\n \"serde\",\n \"tempfile\",\n \"toktier-routing-core\",",
        ) + r#"
[[package]]
name = "tempfile"
version = "3.99.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "9999"
"#;
        assert_eq!(compare(JUDGED, &with_other_tempfile), Ok(()));
    }

    #[test]
    fn a_drifted_transitive_version_is_refused_and_says_how_to_align_it() {
        let drifted = CONSUMER
            .replace("memchr 2.8.3", "memchr 2.8.4")
            .replace("version = \"2.8.3\"", "version = \"2.8.4\"");
        assert_eq!(
            compare(JUDGED, &drifted),
            Err(
                "the judged build compiled memchr 2.8.3; this build compiles 2.8.4. To align \
                 this build, run in the workspace that owns the governing lockfile: \
                 cargo update --precise 2.8.3 memchr"
                    .to_owned()
            )
        );
    }

    #[test]
    fn several_drifted_packages_are_listed_dependents_first() {
        // serde depends on memchr and both drifted: Cargo cannot move
        // memchr down while serde still asks for the newer one, so serde
        // has to be named first. The judged closure's own order puts
        // memchr there instead.
        let drifted = CONSUMER
            .replace("memchr 2.8.3", "memchr 2.8.4")
            .replace("version = \"2.8.3\"", "version = \"2.8.4\"")
            .replace("version = \"1.0.228\"", "version = \"1.0.229\"");
        assert_eq!(
            compare(JUDGED, &drifted),
            Err(
                "2 packages this build compiles are not the judged ones: serde 1.0.228 (this \
                 build compiles 1.0.229); memchr 2.8.3 (this build compiles 2.8.4). To align \
                 this build, run in the workspace that owns the governing lockfile: \
                 cargo update --precise 1.0.228 serde && cargo update --precise 2.8.3 memchr"
                    .to_owned()
            )
        );
    }

    #[test]
    fn a_command_names_the_version_when_the_graph_holds_more_than_one() {
        // Two majors of one package, as a real graph often has: the
        // command has to say which of them it moves.
        let consumer = CONSUMER
            .replace(
                "[[package]]\nname = \"toktier\"\nversion = \"0.2.4\"\nsource",
                "[[package]]\nname = \"memchr\"\nversion = \"1.0.0\"\nsource = \"registry+https://github.com/rust-lang/crates.io-index\"\nchecksum = \"0b0b\"\n\n[[package]]\nname = \"toktier\"\nversion = \"0.2.4\"\nsource",
            )
            .replace(
                "dependencies = [\n \"serde\",\n \"toktier-routing-core\",",
                "dependencies = [\n \"memchr 1.0.0\",\n \"serde\",\n \"toktier-routing-core\",",
            )
            .replace("memchr 2.8.3", "memchr 2.8.4")
            .replace("version = \"2.8.3\"", "version = \"2.8.4\"");
        assert_eq!(
            compare(JUDGED, &consumer),
            Err(
                "the judged build compiled memchr 2.8.3; this build compiles 1.0.0, 2.8.4. To \
                 align this build, run in the workspace that owns the governing lockfile: \
                 cargo update --precise 2.8.3 memchr@2.8.4"
                    .to_owned()
            )
        );
    }

    #[test]
    fn a_judged_package_this_build_does_not_resolve_is_named_as_such() {
        let without = CONSUMER
            .replace("dependencies = [\n \"memchr 2.8.3\",\n]\n", "")
            .replace(
                "[[package]]\nname = \"memchr\"\nversion = \"2.8.3\"\nsource = \"registry+https://github.com/rust-lang/crates.io-index\"\nchecksum = \"bbbb\"\n",
                "",
            );
        assert_eq!(
            compare(JUDGED, &without),
            Err(
                "the judged build compiled memchr 2.8.3; this build resolves no memchr. No \
                 version this build resolves is compatible with the judged one for memchr, so \
                 this build compiles something the judged one did not: matching the judged \
                 feature and target selection is what brings it back"
                    .to_owned()
            )
        );
    }

    #[test]
    fn a_repackaged_registry_crate_is_refused() {
        let repackaged = CONSUMER.replace("checksum = \"bbbb\"", "checksum = \"b0b0\"");
        assert_eq!(
            compare(JUDGED, &repackaged),
            Err(
                "memchr 2.8.3 resolves here as a different copy of the judged package. memchr \
                 resolves from somewhere other than the judged package, so a version change does \
                 not align it: it comes back to the judged copy when the [patch] or source \
                 replacement redirecting it is removed"
                    .to_owned()
            )
        );
    }

    #[test]
    fn a_patched_sibling_source_is_refused() {
        let patched = CONSUMER.replace(
            "source = \"registry+https://github.com/rust-lang/crates.io-index\"\nchecksum = \"ffff\"",
            "source = \"git+https://example.invalid/fork\"",
        );
        assert_eq!(
            compare(JUDGED, &patched),
            Err(
                "toktier-routing-core 0.2.4 resolves here as a different copy of the judged \
                 package. toktier-routing-core resolves from somewhere other than the judged \
                 package, so a version change does not align it: it comes back to the judged \
                 copy when the [patch] or source replacement redirecting it is removed"
                    .to_owned()
            )
        );
    }

    /// Fail-closed: a compiled closure naming something the judged
    /// lockfile does not hold has no content hash behind it, so it
    /// cannot certify anything.
    #[test]
    fn a_closure_the_judged_lockfile_does_not_back_is_refused() {
        let mut judged_closure = compiled();
        judged_closure.push(core_package("phantom", "1.0.0"));
        assert_eq!(
            compare_closures(&parse_lock(JUDGED), &judged_closure, &parse_lock(CONSUMER)),
            Err(
                "the judged compiled closure names phantom 1.0.0, which the judged lockfile \
                 does not hold"
                    .to_owned()
            )
        );
    }

    #[test]
    fn an_empty_closure_certifies_nothing() {
        assert_eq!(
            compare_closures(&parse_lock(JUDGED), &[], &parse_lock(CONSUMER)),
            Err("the judged compiled closure names no package".to_owned())
        );
    }

    /// Fail-closed: a record that could not be read at all -- missing,
    /// truncated, or of another schema -- is a mismatch, never a
    /// `verified`.
    #[test]
    fn an_unreadable_closure_record_is_a_mismatch() {
        let status = dependency_closure_status(
            std::path::Path::new("/nonexistent"),
            &Err("the judged compiled closure is unreadable: no such file".to_owned()),
            &GoverningLock::Found(PathBuf::from("/nonexistent")),
        );
        assert_eq!(
            status,
            "mismatched: the judged compiled closure is unreadable: no such file"
        );
        assert!(!status.starts_with("verified"));
    }

    #[test]
    fn an_unlocated_build_is_told_where_the_judged_records_are() {
        let status = dependency_closure_status(
            std::path::Path::new("/nonexistent"),
            &Ok(compiled()),
            &GoverningLock::Missing,
        );
        assert!(status.starts_with("unlocated: "), "{status}");
        assert!(status.contains(JUDGED_LOCK_RELATIVE), "{status}");
        assert!(status.contains(JUDGED_CLOSURE_RELATIVE), "{status}");
        assert!(status.contains(CARGO_LOCK_ENV), "{status}");
        assert!(status.contains("is not certified"), "{status}");
    }

    // -----------------------------------------------------------------
    // Which packages the certificate speaks for.
    // -----------------------------------------------------------------

    /// The reading the certificate uses is the core one. A package
    /// outside the core that moved is reported, with its command, and
    /// the core answer stays `verified`.
    #[test]
    fn a_package_outside_the_core_is_reported_rather_than_refused() {
        let mut judged_closure = compiled();
        judged_closure.retain(|package| package.name != "memchr");
        judged_closure.push(periphery_package("memchr", "2.8.3"));
        let answers = statuses(judged_closure, &memchr_moved());
        assert_eq!(answers.core_static, "verified");
        assert!(
            answers.strict.starts_with("mismatched: "),
            "{}",
            answers.strict
        );
        assert_eq!(
            answers.advisory,
            "one package outside the certified core is not the judged one; it is reported here \
             and does not enter the certificate: memchr 2.8.3 (this build compiles 2.8.4). To \
             align them anyway, run in the workspace that owns the governing lockfile: cargo \
             update --precise 2.8.3 memchr"
        );
        assert!(answers.r2_drift.is_empty(), "{}", answers.r2_drift);
    }

    /// Several packages outside the core are named together, in the
    /// advisory's own frame: where they are, that they are reported
    /// rather than gating, and the commands that align them anyway. The
    /// frame never calls them harmless.
    #[test]
    fn the_advisory_names_where_the_packages_are_and_what_it_does_not_claim() {
        let mut judged_closure = compiled();
        judged_closure.retain(|package| !["memchr", "serde"].contains(&package.name.as_str()));
        judged_closure.push(periphery_package("memchr", "2.8.3"));
        judged_closure.push(periphery_package("serde", "1.0.228"));
        let drifted = memchr_moved().replace("version = \"1.0.228\"", "version = \"1.0.229\"");
        let answers = statuses(judged_closure, &drifted);
        assert_eq!(
            answers.advisory,
            "2 packages outside the certified core are not the judged ones; they are reported \
             here and do not enter the certificate: serde 1.0.228 (this build compiles 1.0.229); \
             memchr 2.8.3 (this build compiles 2.8.4). To align them anyway, run in the \
             workspace that owns the governing lockfile: cargo update --precise 1.0.228 serde && \
             cargo update --precise 2.8.3 memchr"
        );
        assert_eq!(answers.core_static, "verified");
        for word in ["harmless", "safe", "cannot"] {
            assert!(!answers.advisory.contains(word), "{}", answers.advisory);
        }
    }

    /// The same move inside the core holds the core answer, and there is
    /// nothing to advise about.
    #[test]
    fn a_package_inside_the_core_holds_the_core_answer() {
        let answers = statuses(compiled(), &memchr_moved());
        assert_eq!(answers.core_static, answers.strict);
        assert!(
            answers.core_static.starts_with("mismatched: "),
            "{}",
            answers.core_static
        );
        assert!(answers.advisory.is_empty(), "{}", answers.advisory);
    }

    /// Fail-closed: an entry a record does not classify, or classifies
    /// with a word this reader does not know, decides the certificate
    /// rather than being reported beside it.
    #[test]
    fn an_unclassified_entry_is_read_as_core() {
        assert_eq!(Tier::from_record(None), Tier::Core);
        assert_eq!(Tier::from_record(Some("")), Tier::Core);
        assert_eq!(Tier::from_record(Some("advisory")), Tier::Core);
        assert_eq!(Tier::from_record(Some("periphery")), Tier::Periphery);
        // And end to end: the same drift as above, from a record whose
        // entries carry no tier at all.
        let answers = statuses(compiled(), &memchr_moved());
        assert!(
            answers.core_static.starts_with("mismatched: "),
            "{}",
            answers.core_static
        );
    }

    /// A core package whose behaviour version the runtime reads is not
    /// compared by package version here: the move is handed over as
    /// drift, and the core answer waits for the probe.
    #[test]
    fn a_probed_package_hands_its_version_move_to_the_runtime() {
        let mut judged_closure = compiled();
        judged_closure.retain(|package| package.name != "memchr");
        judged_closure.push(probed_package("memchr", "2.8.3", "regex"));
        let answers = statuses(judged_closure, &memchr_moved());
        assert_eq!(answers.core_static, "verified");
        assert_eq!(
            answers.r2_drift,
            format!("regex{RECORD_SEPARATOR}memchr 2.8.3 -> 2.8.4")
        );
        assert!(answers.advisory.is_empty(), "{}", answers.advisory);
        assert!(
            answers.strict.starts_with("mismatched: "),
            "{}",
            answers.strict
        );
    }

    /// A probed package that resolves from somewhere other than the
    /// judged one is not a version that moved, so no probe can answer
    /// for it and it stays with the exact comparison.
    #[test]
    fn a_probed_package_from_another_source_stays_with_the_exact_comparison() {
        let mut judged_closure = compiled();
        judged_closure.retain(|package| package.name != "memchr");
        judged_closure.push(probed_package("memchr", "2.8.3", "regex"));
        let repackaged = CONSUMER.replace("checksum = \"bbbb\"", "checksum = \"b0b0\"");
        let answers = statuses(judged_closure, &repackaged);
        assert!(
            answers
                .core_static
                .contains("a different copy of the judged package"),
            "{}",
            answers.core_static
        );
        assert!(answers.r2_drift.is_empty(), "{}", answers.r2_drift);
    }

    /// A record that disagrees with itself about a unit's behaviour
    /// version leaves that unit out, which puts every package of it back
    /// on the exact comparison.
    #[test]
    fn a_unit_two_entries_disagree_about_is_not_probed() {
        let mut judged_closure = compiled();
        judged_closure.retain(|package| package.name != "memchr");
        judged_closure.push(probed_package("memchr", "2.8.3", "regex"));
        let mut other = probed_package("serde", "1.0.228", "regex");
        other.behavior_version = Some("17.0".to_owned());
        judged_closure.retain(|package| package.name != "serde");
        judged_closure.push(other);
        let answers = statuses(judged_closure, &memchr_moved());
        assert!(
            answers.judged_behavior.is_empty(),
            "{}",
            answers.judged_behavior
        );
        assert!(
            answers.core_static.starts_with("mismatched: "),
            "{}",
            answers.core_static
        );
        assert!(answers.r2_drift.is_empty(), "{}", answers.r2_drift);
    }

    /// A unit whose behaviour version is its package version is compared
    /// here rather than probed, so it never appears in the drift line.
    #[test]
    fn a_unit_read_from_its_crate_version_is_compared_exactly() {
        let mut judged_closure = compiled();
        judged_closure.retain(|package| package.name != "memchr");
        let mut package = probed_package("memchr", "2.8.3", "counted-by-version");
        package.behavior_source = Some(CRATE_VERSION_BEHAVIOR_SOURCE.to_owned());
        package.behavior_version = Some("crate:2.8.3".to_owned());
        judged_closure.push(package);
        let answers = statuses(judged_closure, &memchr_moved());
        assert!(
            answers.core_static.starts_with("mismatched: "),
            "{}",
            answers.core_static
        );
        assert!(answers.r2_drift.is_empty(), "{}", answers.r2_drift);
        assert!(
            answers.judged_behavior.is_empty(),
            "{}",
            answers.judged_behavior
        );
    }

    /// The judged behaviour versions travel as one record per unit, in a
    /// fixed order, so the runtime reads them without a parser of its
    /// own.
    #[test]
    fn the_judged_behaviour_versions_travel_one_record_per_unit() {
        let mut judged_closure = compiled();
        judged_closure.retain(|package| !["memchr", "serde"].contains(&package.name.as_str()));
        judged_closure.push(probed_package("memchr", "2.8.3", "regex"));
        judged_closure.push(probed_package("serde", "1.0.228", "regex"));
        let answers = statuses(judged_closure, CONSUMER);
        assert_eq!(
            answers.judged_behavior,
            format!("regex{RECORD_SEPARATOR}16.0{RECORD_SEPARATOR}probe:regex-age")
        );
        assert_eq!(answers.core_static, "verified");
    }

    /// Splitting the report does not split the commands out of order:
    /// each side carries the packages it names, and a core package that
    /// depends on a periphery one still comes first inside its own list.
    #[test]
    fn each_side_of_the_split_carries_its_own_runnable_commands() {
        let mut judged_closure = compiled();
        judged_closure.retain(|package| package.name != "memchr");
        judged_closure.push(periphery_package("memchr", "2.8.3"));
        let drifted = memchr_moved().replace("version = \"1.0.228\"", "version = \"1.0.229\"");
        let answers = statuses(judged_closure, &drifted);
        // serde is core and memchr is periphery; each report names one
        // package and carries the command for that package alone.
        assert_eq!(
            answers.core_static,
            "mismatched: the judged build compiled serde 1.0.228; this build compiles 1.0.229. \
             To align this build, run in the workspace that owns the governing lockfile: cargo \
             update --precise 1.0.228 serde"
        );
        assert_eq!(
            answers.advisory,
            "one package outside the certified core is not the judged one; it is reported here \
             and does not enter the certificate: memchr 2.8.3 (this build compiles 2.8.4). To \
             align them anyway, run in the workspace that owns the governing lockfile: cargo \
             update --precise 2.8.3 memchr"
        );
        // The whole-closure reading still holds both, dependents first.
        assert!(
            answers
                .strict
                .contains("2 packages this build compiles are not the judged ones")
                && answers.strict.find("serde").unwrap() < answers.strict.find("memchr").unwrap(),
            "{}",
            answers.strict
        );
    }

    /// A build that cannot be compared says so on the core reading and
    /// advises about nothing: there is no comparison to draw an advisory
    /// from.
    #[test]
    fn a_build_that_cannot_be_compared_advises_about_nothing() {
        let unlocated = closure_statuses(
            std::path::Path::new("/nonexistent"),
            &Ok(compiled()),
            &GoverningLock::Missing,
        );
        assert!(unlocated.core_static.starts_with("unlocated: "));
        assert_eq!(unlocated.core_static, unlocated.strict);
        assert!(unlocated.advisory.is_empty());
        assert!(unlocated.r2_drift.is_empty());

        let broken = closure_statuses(
            std::path::Path::new("/nonexistent"),
            &Err("the judged compiled closure is unreadable: no such file".to_owned()),
            &GoverningLock::Found(PathBuf::from("/nonexistent")),
        );
        assert_eq!(
            broken.core_static,
            "mismatched: the judged compiled closure is unreadable: no such file"
        );
        assert!(broken.advisory.is_empty());
        assert!(broken.judged_behavior.is_empty());
    }

    /// The whole-closure reading is the one 0.2.5 produced, to the byte.
    /// Splitting the answer added readings; it did not reword this one.
    #[test]
    fn the_whole_closure_reading_is_unchanged() {
        let mut judged_closure = compiled();
        judged_closure.retain(|package| package.name != "memchr");
        judged_closure.push(periphery_package("memchr", "2.8.3"));
        let answers = statuses(judged_closure, &memchr_moved());
        assert_eq!(
            answers.strict,
            "mismatched: the judged build compiled memchr 2.8.3; this build compiles 2.8.4. To \
             align this build, run in the workspace that owns the governing lockfile: cargo \
             update --precise 2.8.3 memchr"
        );
        // And the two producers of that reading answer alike: the
        // whole-closure status function is the same comparison, asked
        // for one subset instead of four.
        let temporary = tempfile::tempdir().unwrap();
        let judged_lock = temporary.path().join("judged.lock");
        let governing = temporary.path().join("Cargo.lock");
        fs::write(&judged_lock, JUDGED).unwrap();
        fs::write(&governing, memchr_moved()).unwrap();
        assert_eq!(
            answers.strict,
            dependency_closure_status(
                &judged_lock,
                &Ok(compiled()),
                &GoverningLock::Found(governing),
            )
        );
    }

    #[test]
    fn every_status_stays_on_one_line() {
        // The build script hands this string to Cargo as one
        // `cargo:rustc-env` directive, which ends at the first newline.
        let drifted = CONSUMER
            .replace("memchr 2.8.3", "memchr 2.8.4")
            .replace("version = \"2.8.3\"", "version = \"2.8.4\"");
        let mut judged_closure = compiled();
        judged_closure.retain(|package| package.name != "memchr");
        judged_closure.push(periphery_package("memchr", "2.8.3"));
        judged_closure.push(probed_package("serde", "1.0.228", "regex"));
        judged_closure.retain(|package| package.name != "serde" || package.behavior_unit.is_some());
        let split = statuses(judged_closure, &drifted);
        let lines = [
            dependency_closure_status(
                std::path::Path::new("/nonexistent"),
                &Ok(compiled()),
                &GoverningLock::Missing,
            ),
            dependency_closure_status(
                std::path::Path::new("/nonexistent"),
                &Ok(compiled()),
                &GoverningLock::JudgedRecordNamed(PathBuf::from("/somewhere/judged.lock")),
            ),
            compare(JUDGED, &drifted).unwrap_err(),
            compare(JUDGED, CONSUMER)
                .map(|()| "verified".to_owned())
                .unwrap(),
            split.strict,
            split.core_static,
            split.r2_drift,
            split.advisory,
            split.judged_behavior,
        ];
        for status in lines {
            assert!(!status.contains('\n'), "{status}");
        }
    }

    // -----------------------------------------------------------------
    // Naming the judged record instead of a lockfile of this build.
    // -----------------------------------------------------------------

    /// An unpacked registry copy: a manifest directory carrying the
    /// judged records, and no sibling crates above it.
    fn packaged_crate(root: &Path) -> PathBuf {
        let manifest = root.join("unpacked/toktier-0.2.4");
        fs::create_dir_all(manifest.join("data/build")).unwrap();
        fs::write(manifest.join(JUDGED_LOCK_RELATIVE), JUDGED).unwrap();
        manifest
    }

    fn out_dir(root: &Path) -> PathBuf {
        let path = root.join("target/debug/build/toktier-abc/out");
        fs::create_dir_all(&path).unwrap();
        path
    }

    #[test]
    fn a_packaged_build_pointed_at_its_own_judged_record_is_refused() {
        // B5: the file as it sits inside the unpacked crate.
        let temporary = tempfile::tempdir().unwrap();
        let manifest = packaged_crate(temporary.path());
        let named = manifest.join(JUDGED_LOCK_RELATIVE);
        let located = locate_governing_lock_from(
            Some(named.clone()),
            &out_dir(temporary.path()),
            Consumption::Packaged(&manifest),
        );
        let GoverningLock::JudgedRecordNamed(path) = located else {
            panic!("the judged record was taken for a governing lockfile");
        };
        assert_eq!(path, named);
    }

    #[test]
    fn a_path_dressed_up_to_leave_the_package_data_directory_is_still_refused() {
        // B5, written the long way round. The two sides are resolved
        // before they are compared, so `..` changes nothing.
        let temporary = tempfile::tempdir().unwrap();
        let manifest = packaged_crate(temporary.path());
        let named = manifest.join("data/build/../../data/build/judged_dependencies.lock");
        assert!(matches!(
            locate_governing_lock_from(
                Some(named),
                &out_dir(temporary.path()),
                Consumption::Packaged(&manifest),
            ),
            GoverningLock::JudgedRecordNamed(_)
        ));
    }

    #[test]
    fn a_copy_of_the_judged_record_kept_elsewhere_is_refused_too() {
        // B6: moving the bytes out of `data/` does not make them an
        // account of this build.
        let temporary = tempfile::tempdir().unwrap();
        let manifest = packaged_crate(temporary.path());
        let elsewhere = temporary.path().join("elsewhere/Cargo.lock");
        fs::create_dir_all(elsewhere.parent().unwrap()).unwrap();
        fs::copy(manifest.join(JUDGED_LOCK_RELATIVE), &elsewhere).unwrap();
        assert!(matches!(
            locate_governing_lock_from(
                Some(elsewhere),
                &out_dir(temporary.path()),
                Consumption::Packaged(&manifest),
            ),
            GoverningLock::JudgedRecordNamed(_)
        ));
    }

    #[test]
    fn a_real_consumer_lockfile_is_still_taken_as_the_governing_one() {
        // B7/B8: the ordinary, supported use of the variable. A
        // consumer's own lockfile holds its own package and reaches
        // toktier from a registry, so it can be neither of the two
        // signals -- whether or not it is aligned.
        let temporary = tempfile::tempdir().unwrap();
        let manifest = packaged_crate(temporary.path());
        let consumer = temporary.path().join("consumer/Cargo.lock");
        fs::create_dir_all(consumer.parent().unwrap()).unwrap();
        fs::write(&consumer, CONSUMER).unwrap();
        let located = locate_governing_lock_from(
            Some(consumer.clone()),
            &out_dir(temporary.path()),
            Consumption::Packaged(&manifest),
        );
        let GoverningLock::Found(path) = located else {
            panic!("a consumer's own lockfile was refused");
        };
        assert_eq!(path, consumer);
        // And the comparison it feeds still answers the way it did.
        assert_eq!(
            dependency_closure_status(
                &manifest.join(JUDGED_LOCK_RELATIVE),
                &Ok(compiled()),
                &GoverningLock::Found(consumer),
            ),
            "verified"
        );
    }

    #[test]
    fn a_workspace_build_may_name_the_shipped_copy_of_its_own_lockfile() {
        // B2: the exemption. In a workspace `data/build/...lock` is a byte
        // copy of the lockfile that really does govern the build (the
        // check further down this file pins that), so naming it is
        // naming the right file by another name.
        let temporary = tempfile::tempdir().unwrap();
        let manifest = temporary.path().join("crates/toktier");
        fs::create_dir_all(manifest.join("data/build")).unwrap();
        fs::create_dir_all(temporary.path().join("crates/toktier-routing-core")).unwrap();
        let workspace_lock = temporary.path().join("Cargo.lock");
        fs::write(&workspace_lock, JUDGED).unwrap();
        let shipped = manifest.join(JUDGED_LOCK_RELATIVE);
        fs::copy(&workspace_lock, &shipped).unwrap();
        let located = locate_governing_lock_from(
            Some(shipped.clone()),
            &out_dir(temporary.path()),
            Consumption::Workspace(&manifest),
        );
        let GoverningLock::Found(path) = located else {
            panic!("a workspace build was refused its own lockfile");
        };
        assert_eq!(path, shipped);
    }

    #[test]
    fn a_named_path_that_is_not_a_file_leaves_the_build_unlocated() {
        // B9, unchanged.
        let temporary = tempfile::tempdir().unwrap();
        let manifest = packaged_crate(temporary.path());
        assert!(matches!(
            locate_governing_lock_from(
                Some(temporary.path().join("no-such-lockfile")),
                &out_dir(temporary.path()),
                Consumption::Packaged(&manifest),
            ),
            GoverningLock::Missing
        ));
    }

    #[test]
    fn anything_else_under_the_package_data_directory_is_refused_as_well() {
        // B10: `data/` carries the records that travel with the crate and
        // nothing that governs a build, so the whole directory is read
        // the same way.
        let temporary = tempfile::tempdir().unwrap();
        let manifest = packaged_crate(temporary.path());
        let other = manifest.join("data/src/support_registry.v1.json");
        fs::create_dir_all(other.parent().unwrap()).unwrap();
        fs::write(&other, "{}").unwrap();
        assert!(matches!(
            locate_governing_lock_from(
                Some(other),
                &out_dir(temporary.path()),
                Consumption::Packaged(&manifest),
            ),
            GoverningLock::JudgedRecordNamed(_)
        ));
    }

    #[test]
    fn a_packaged_build_with_the_variable_unset_looks_only_above_out_dir() {
        // B4: the manifest's own ancestors stay out of the search, so a
        // registry copy cannot find its own shipped lockfile by walking.
        let temporary = tempfile::tempdir().unwrap();
        let manifest = packaged_crate(temporary.path());
        fs::write(manifest.join("Cargo.lock"), CONSUMER).unwrap();
        assert!(matches!(
            locate_governing_lock_from(
                None,
                &out_dir(temporary.path()),
                Consumption::Packaged(&manifest)
            ),
            GoverningLock::Missing
        ));
    }

    #[test]
    fn a_workspace_build_with_the_variable_unset_walks_up_from_the_manifest() {
        // B1/B3, unchanged: the workspace lockfile is found even when
        // OUT_DIR sits somewhere else entirely.
        let temporary = tempfile::tempdir().unwrap();
        let manifest = temporary.path().join("crates/toktier");
        fs::create_dir_all(&manifest).unwrap();
        let workspace_lock = temporary.path().join("Cargo.lock");
        fs::write(&workspace_lock, JUDGED).unwrap();
        let elsewhere = temporary.path().join("elsewhere/out");
        fs::create_dir_all(&elsewhere).unwrap();
        let located =
            locate_governing_lock_from(None, &elsewhere, Consumption::Workspace(&manifest));
        let GoverningLock::Found(path) = located else {
            panic!("the workspace lockfile was not found");
        };
        assert_eq!(path, workspace_lock);
    }

    #[test]
    fn naming_the_judged_record_is_answered_rather_than_compared() {
        // The status string a refused build reads: it says what the file
        // is, that this build is not certified, and both routes out.
        let status = dependency_closure_status(
            std::path::Path::new("/nonexistent"),
            &Ok(compiled()),
            &GoverningLock::JudgedRecordNamed(PathBuf::from("/crate/data/build/judged.lock")),
        );
        assert!(status.starts_with("unlocated: "), "{status}");
        assert!(status.contains(CARGO_LOCK_ENV), "{status}");
        assert!(status.contains("/crate/data/build/judged.lock"), "{status}");
        assert!(status.contains(JUDGED_LOCK_RELATIVE), "{status}");
        assert!(status.contains("is not certified"), "{status}");
        assert!(
            status.contains("align this build's own lockfile"),
            "{status}"
        );
        assert!(status.contains("build inside a workspace"), "{status}");
        assert!(!status.starts_with("verified"), "{status}");
    }

    /// The reader accepts one lockfile shape. If Cargo ever writes a
    /// package's dependency array inline, every package parses as a
    /// leaf, the closure shrinks to the root, and the comparison could
    /// answer `verified` about a graph it never read. The declared
    /// format version is what says whether that has happened, so an
    /// unknown or missing one is refused rather than parsed.
    #[test]
    fn a_lockfile_format_this_reader_does_not_know_is_refused() {
        assert_eq!(lock_format_version(JUDGED), Some(4));
        assert!(SUPPORTED_LOCK_VERSIONS.contains(&4));
        assert!(check_lock_format("fixture", JUDGED).is_ok());

        let unknown = JUDGED.replace("version = 4", "version = 99");
        let refusal = check_lock_format("the governing lockfile", &unknown).unwrap_err();
        assert!(
            refusal.contains("format 99") && refusal.contains("the governing lockfile"),
            "{refusal}"
        );

        let undeclared = JUDGED.replace("version = 4\n", "");
        assert_eq!(lock_format_version(&undeclared), None);
        assert!(check_lock_format("fixture", &undeclared).is_err());

        // The workspace's own lockfile is one this reader knows.
        let workspace = std::fs::read_to_string(workspace_root().join("Cargo.lock")).unwrap();
        assert!(check_lock_format("the workspace lockfile", &workspace).is_ok());
    }

    /// The other half of the same failure: a root that parsed with no
    /// edges at all. This crate has dependencies in every
    /// configuration, so that is a shape the reader could not follow,
    /// not a leaf, and comparing from it would judge the root alone.
    #[test]
    fn a_root_with_no_dependency_edges_is_refused() {
        let flattened = CONSUMER.replace(
            "dependencies = [\n \"serde\",\n \"toktier-routing-core\",\n]",
            "dependencies = [\"serde\", \"toktier-routing-core\"]",
        );
        assert!(
            flattened != CONSUMER,
            "the fixture's root dependency block was not rewritten"
        );
        assert_eq!(
            compare(JUDGED, &flattened),
            Err("the governing lockfile's toktier entry lists no dependencies".to_owned())
        );
    }

    #[test]
    fn a_lockfile_without_the_root_is_refused() {
        let without = CONSUMER.replace("name = \"toktier\"", "name = \"somebody-else\"");
        assert_eq!(
            compare(JUDGED, &without),
            Err("no toktier package in the governing lockfile".to_owned())
        );
    }

    fn workspace_root() -> std::path::PathBuf {
        std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .and_then(std::path::Path::parent)
            .unwrap()
            .to_path_buf()
    }

    #[test]
    fn the_shipped_judged_lockfile_matches_the_workspace_lockfile() {
        // The packaged copy is what a registry build compares against;
        // a stale copy would judge the wrong graph.
        let workspace = std::fs::read(workspace_root().join("Cargo.lock")).unwrap();
        let packaged = std::fs::read(
            std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join(super::JUDGED_LOCK_RELATIVE),
        )
        .unwrap();
        assert_eq!(workspace, packaged);
    }

    /// The two shipped records have to agree, and the smaller one has to
    /// be smaller: a compiled closure the size of the lockfile closure
    /// would mean the narrowing silently did nothing.
    #[test]
    fn the_shipped_closure_is_backed_by_the_shipped_lockfile_and_narrower() {
        let text = std::fs::read_to_string(
            std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join(JUDGED_CLOSURE_RELATIVE),
        )
        .unwrap();
        let packages =
            parse_lock(&std::fs::read_to_string(workspace_root().join("Cargo.lock")).unwrap());
        let reachable = closure(&packages, super::CLOSURE_ROOT);
        // The record is generated, so this reads its entries without a
        // JSON dependency the shared module does not have.
        let mut entries = Vec::new();
        let mut name: Option<String> = None;
        for line in text.lines().map(str::trim) {
            if let Some(value) = line.strip_prefix("\"name\": \"") {
                name = value.strip_suffix("\",").map(str::to_owned);
            } else if let Some(value) = line.strip_prefix("\"version\": \"") {
                let version = value.trim_end_matches('"').trim_end_matches("\",");
                if let Some(name) = name.take() {
                    entries.push((name, version.to_owned()));
                }
            }
        }
        assert!(!entries.is_empty());
        assert!(
            entries.len() < reachable.len(),
            "{} compiled vs {} reachable",
            entries.len(),
            reachable.len()
        );
        for (name, version) in &entries {
            assert!(
                reachable
                    .iter()
                    .any(|package| &package.name == name && &package.version == version),
                "{name} {version} is not in the judged lockfile"
            );
        }
    }
}
