# Verify the shipped evidence manifests in evidence/.
"""Check the machine-readable evidence manifests.

A manifest states what was run and what was observed; it claims nothing
beyond that (``docs/contracts/registry.md`` Section 5). The manifests are
produced by maintainer tooling from the recorded campaign readings; those
generation inputs are not part of this repository. What ships here is the
verification surface: serialisation, schema and root digest. A hand edit
fails ``--check``.

Calibers worth stating, because the schema field names are shorter than the
quantities they carry:

* ``corpora[].docs`` and ``totals.docs`` count *distinct documents in the
  judged corpus*. The number of individual comparisons is larger by the number
  of families; it is carried per artifact in the registry readings.
* ``bytes`` carries the recorded character count (Unicode code points). UTF-8
  never encodes a code point in less than one byte, so this is a strict lower
  bound on the byte volume and never overstates it.
* ``mismatches`` is recorded as read.
* ``routed`` counts documents that contain an added-token literal and are
  answered by the reference frontend by design, kept in its own column rather
  than counted as accelerated passes.

Two deliberate omissions:

* ``environment.hosts`` is not written: host names are deliberately omitted;
  the GPU models, which do carry evidence, are written.
* ``corpora[].shard_digests`` is written only when every judged shard has a
  recorded digest. Part of the campaign read the corpus in place instead of
  staging it, and those groups recorded no shard digest; a partial list
  published without that qualification would read as complete coverage.

Usage::

    python tools/generate_evidence.py --check --campaign main
    python tools/generate_evidence.py --check --campaign extra
    python tools/generate_evidence.py --check --campaign kimi
    python tools/generate_evidence.py --check --campaign fastokens_pinned

For the ``fastokens_pinned`` campaign ``routed`` counts documents the adapter's
Unicode guard answers by the reference by design, and ``mismatches`` is the
guarded count; the raw count is carried in the registry's
``engine_distributions.fastokens.evidence`` node beside it.

The check needs the ``jsonschema`` package (in the ``test`` dependency
group; not a runtime dependency of the library).
"""

import argparse
import sys
from pathlib import Path

from registry_common import (
    EVIDENCE_DOMAIN_TAG,
    GenerationError,
    load_json,
    verify_file,
)

TOOL_NAME = "tools/generate_evidence.py"
# One tool identity, two halves: the maintainer-side generator writes the
# manifests and stamps this version into their ``generated_by``; this
# verification half moves in lockstep with it. 1.1.0 is the generator
# version that produced the shipped documents.
TOOL_VERSION = "1.1.0"

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
SCHEMA_PATH = REPOSITORY_ROOT / "schemas" / "evidence_manifest.schema.json"
DEFAULT_OUTPUTS = {
    "main": REPOSITORY_ROOT / "evidence" / "evidence_manifest.json",
    "extra": REPOSITORY_ROOT / "evidence" / "evidence_manifest_added_families.json",
    "kimi": REPOSITORY_ROOT / "evidence" / "evidence_manifest_kimi_band.json",
    "fastokens_pinned": (
        REPOSITORY_ROOT / "evidence" / "evidence_manifest_fastokens_pinned.json"
    ),
}


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Check a shipped evidence manifest."
    )
    parser.add_argument("--campaign", choices=sorted(DEFAULT_OUTPUTS), default="main")
    parser.add_argument("--out", type=Path)
    parser.add_argument("--check", action="store_true")
    return parser


def main(argv: list[str] | None = None) -> int:
    arguments = build_parser().parse_args(argv)
    if not arguments.check:
        raise GenerationError(
            "this tool verifies the shipped manifests (--check); the "
            "manifests themselves are generated by the maintainers from "
            "the recorded campaign readings"
        )
    schema = load_json(SCHEMA_PATH)
    output = arguments.out or DEFAULT_OUTPUTS[arguments.campaign]
    problems = verify_file(output, schema, EVIDENCE_DOMAIN_TAG)
    for problem in problems:
        print(f"error: {problem}", file=sys.stderr)
    if problems:
        return 1
    print(f"{output}: check passed")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except GenerationError as error:  # pragma: no cover - command line surface
        print(f"error: {error}", file=sys.stderr)
        raise SystemExit(2) from error
