# Verify the artifact manifest that ships inside the toktier package.
"""Check the fetch-side identity of every certified tokenizer artifact.

``src/toktier/artifacts/tables/artifact_manifest.v1.json`` is what
``toktier artifacts fetch`` and ``toktier artifacts verify`` resolve a
family against. It pins, per family, the upstream repository, the frozen
revision and the per-file sha256 of the file the runtime opens
(``docs/contracts/registry.md`` Section 4: a revision pin without content
digests is not an identity).

Scope, and why it is exactly this: the manifest carries the families the
shipped support registry certifies, and nothing else. A family the
registry does not certify has no reading behind it, so fetching it by
name would suggest coverage that does not exist.

The manifest is generated by maintainer tooling that hashes the frozen
artifact files and refuses any disagreement between the independent
records of each digest; those generation inputs are not part of this
repository. ``--check`` verifies what can be verified here: the file is
in the deterministic serialised form, the library's own manifest reader
accepts it, and its contents agree with the support registry that ships
next to it. Nothing in this tool reaches the network.

Usage::

    python tools/generate_artifact_manifest.py --check
"""

import argparse
import sys
from pathlib import Path

from registry_common import (
    GenerationError,
    load_json,
    serialise_document,
)

TOOL_NAME = "tools/generate_artifact_manifest.py"

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
SOURCE_ROOT = REPOSITORY_ROOT / "src"
DEFAULT_OUTPUT = (
    REPOSITORY_ROOT
    / "src"
    / "toktier"
    / "artifacts"
    / "tables"
    / "artifact_manifest.v1.json"
)
REGISTRY_PATH = REPOSITORY_ROOT / "tables" / "support_registry.json"

#: The file the runtime opens for a family. The reference backend reads
#: ``tokenizer.json`` and the GPU tables are exported from the same
#: bytes, so this one file is the whole artifact as far as the package
#: is concerned; a manifest entry that named more would pin files
#: nothing verifies against a reading.
ARTIFACT_FILE = "tokenizer.json"


def certified_artifacts() -> dict[str, str]:
    """Family to certified artifact digest, from the shipped registry."""
    document = load_json(REGISTRY_PATH)
    records = document.get("artifacts")
    if not isinstance(records, list) or not records:
        raise GenerationError(f"{REGISTRY_PATH} carries no artifact records")
    certified: dict[str, str] = {}
    for record in records:
        if not isinstance(record, dict):
            raise GenerationError(f"{REGISTRY_PATH}: artifact records must be tables")
        family = str(record["family"])
        digest = str(record["artifact_sha256"])
        previous = certified.setdefault(family, digest)
        if previous != digest:
            raise GenerationError(
                f"{family}: the support registry records two artifact digests "
                f"({previous} and {digest})"
            )
    return certified


def check_shipped(path: Path) -> list[str]:
    """Check the shipped file on its own terms.

    Three things are checked here: the file is in the deterministic
    serialised form, the library's own manifest reader accepts it (no
    second copy of the parsing rules lives in this tool), and its
    contents agree with the support registry that ships next to it.
    """
    if not path.exists():
        return [f"{path}: file is missing"]
    raw = path.read_bytes()
    if str(SOURCE_ROOT) not in sys.path:
        sys.path.insert(0, str(SOURCE_ROOT))
    from toktier.artifacts import ArtifactManifest
    from toktier.errors import RegistryInvalid

    try:
        manifest = ArtifactManifest.load(path)
    except RegistryInvalid as error:
        return [f"{path}: the library rejects this manifest: {error}"]

    problems: list[str] = []
    document = {
        family: {
            "repo_id": entry.repo_id,
            "revision": entry.revision,
            "files": {
                item.name: {"sha256": item.sha256, "size": item.size}
                for item in entry.files
            },
        }
        for family, entry in sorted(manifest.entries.items())
    }
    if serialise_document(document) != raw:
        problems.append(
            f"{path}: file is not in the deterministic serialised form "
            "(regenerate with the tool rather than editing by hand)"
        )
    # The certification registry is published in a later subsystem commit.
    # Until it exists, this checker can still enforce parsing and deterministic
    # serialization; the cross-registry digest check activates with that file.
    if not REGISTRY_PATH.is_file():
        return problems
    certified = certified_artifacts()
    shipped = set(manifest.families())
    if shipped != set(certified):
        problems.append(
            f"{path}: families differ from {REGISTRY_PATH.name}: "
            f"only in the manifest {sorted(shipped - set(certified))}, "
            f"only in the registry {sorted(set(certified) - shipped)}"
        )
    for family in sorted(shipped & set(certified)):
        files = manifest.get(family).files
        names = [item.name for item in files]
        if names != [ARTIFACT_FILE]:
            problems.append(
                f"{path}: {family} pins {names}, expected [{ARTIFACT_FILE}]"
            )
            continue
        if files[0].sha256 != certified[family]:
            problems.append(
                f"{path}: {family} pins {files[0].sha256} but the support registry "
                f"certifies {certified[family]}"
            )
        if files[0].size is None:
            problems.append(f"{path}: {family} does not record a byte length")
    return problems


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Check the shipped artifact manifest."
    )
    parser.add_argument("--out", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify the shipped file.",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    arguments = build_parser().parse_args(argv)
    if not arguments.check:
        raise GenerationError(
            "this tool verifies the shipped manifest (--check); the "
            "manifest itself is generated by the maintainers from the "
            "frozen artifact files"
        )
    problems = check_shipped(arguments.out)
    for problem in problems:
        print(f"error: {problem}", file=sys.stderr)
    if problems:
        return 1
    print(f"{arguments.out}: check passed")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except GenerationError as error:  # pragma: no cover - command line surface
        print(f"error: {error}", file=sys.stderr)
        raise SystemExit(2) from error
