# Verify readings/readme_backfill.json, the documentation reading record.
"""Check the resolved documentation placeholder keys.

The documentation carries ``TODO:number:`` / ``TODO:pending:`` placeholder
markers instead of numbers so that no figure enters the prose by hand.
``readings/readme_backfill.json`` records, per key: kind, value, the record
the value was read from, and a note. It is produced by maintainer tooling
from the recorded campaign and benchmark readings; those generation inputs
are not part of this repository.

``--check`` verifies what can be verified here: the file parses, it is in
the deterministic serialised form, and every marker key still present in the
documentation has an entry. A hand edit that breaks the serialised form
fails it.

Usage::

    python tools/generate_readme_backfill.py --check
"""

import argparse
import json
import re
import sys
from pathlib import Path

from registry_common import GenerationError, serialise_document

TOOL_NAME = "tools/generate_readme_backfill.py"
# One tool identity, two halves: the maintainer-side generator writes the
# reading record and stamps this version into its ``generated_by``; this
# verification half moves in lockstep with it. 1.1.0 is the generator
# version that produced the shipped record.
TOOL_VERSION = "1.1.0"

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = REPOSITORY_ROOT / "readings" / "readme_backfill.json"

MARKER = re.compile(
    r"<!--\s*TODO:(?P<kind>number|pending):(?P<key>[A-Za-z0-9_.]+)\s*-->"
)


def scan_markers(root: Path) -> dict[str, str]:
    """Return ``key -> kind`` for every marker in the documentation."""
    found: dict[str, str] = {}
    for path in sorted(root.rglob("*.md")):
        if any(part in {".git", "target", ".venv"} for part in path.parts):
            continue
        for match in MARKER.finditer(path.read_text(encoding="utf-8")):
            found[match.group("key")] = match.group("kind")
    return found


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Check the resolved documentation placeholder keys."
    )
    parser.add_argument("--out", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    return parser


def main(argv: list[str] | None = None) -> int:
    arguments = build_parser().parse_args(argv)
    if not arguments.check:
        raise GenerationError(
            "this tool verifies the shipped reading record (--check); the "
            "record itself is generated by the maintainers from the "
            "recorded readings"
        )
    if not arguments.out.is_file():
        print(f"error: {arguments.out}: file is missing", file=sys.stderr)
        return 1
    raw = arguments.out.read_bytes()
    try:
        existing = json.loads(raw.decode("utf-8"))
    except (UnicodeDecodeError, ValueError) as error:
        print(f"error: {arguments.out}: cannot parse: {error}", file=sys.stderr)
        return 1
    problems = []
    if serialise_document(existing) != raw:
        problems.append("file is not in the deterministic serialised form")
    keys = existing.get("keys") if isinstance(existing, dict) else None
    recorded = set(keys) if isinstance(keys, dict) else set()
    for key in sorted(scan_markers(REPOSITORY_ROOT)):
        if key not in recorded:
            problems.append(f"marker key {key} has no entry in the record")
    for problem in problems:
        print(f"error: {arguments.out}: {problem}", file=sys.stderr)
    if problems:
        return 1
    print(f"{arguments.out}: check passed")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except GenerationError as error:  # pragma: no cover - command line surface
        print(f"error: {error}", file=sys.stderr)
        raise SystemExit(2) from error
