# Verify the artifact manifest that ships inside the toktier package.
"""Check the fetch-side identity of every certified tokenizer artifact.

``src/toktier/artifacts/tables/artifact_manifest.v1.json`` is what
``toktier artifacts fetch`` and ``toktier artifacts verify`` resolve a
family against. It pins, per family, the upstream repository, the frozen
revision and the per-file sha256 of the loader-face input closure: every
file the pinned loader reads when it materializes the certified loader
face from the frozen artifact directory (``docs/contracts/registry.md``
Section 4: a revision pin without content digests is not an identity).
The certification subject is materialized on that file group, so a
manifest that pinned less would build caches the certified face cannot
be rebuilt from; since 0.2.9 the closure is measured and proven at
generation time.

Scope, and why it is exactly this: the manifest carries the families the
shipped support registry certifies, and nothing else. A family the
registry does not certify has no reading behind it, so fetching it by
name would suggest coverage that does not exist.

The manifest is generated by maintainer tooling that materializes each
frozen artifact directory under a read trace, pins what the loader
consumed, and refuses any disagreement between the independent records
of each digest; those generation inputs are not part of this repository.
``--check`` verifies what can be verified here: the file is in the
deterministic serialised form, the library's own manifest reader accepts
it, its contents agree with the support registry that ships next to it,
and every registry record that declares configuration-side added tokens
has its source file pinned. Nothing in this tool reaches the network.

Usage::

    python tools/generate_artifact_manifest.py --check
"""

import argparse
import sys
from pathlib import Path
from typing import Any

from registry_common import (
    GenerationError,
    load_json,
    serialise_document,
)

TOOL_NAME = "tools/generate_artifact_manifest.py"

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
SOURCE_ROOT = REPOSITORY_ROOT / "src"
DEFAULT_OUTPUT = (
    REPOSITORY_ROOT
    / "src"
    / "toktier"
    / "artifacts"
    / "tables"
    / "artifact_manifest.v1.json"
)
REGISTRY_PATH = REPOSITORY_ROOT / "tables" / "support_registry.json"

#: The artifact file. Its digest is the certified artifact identity of
#: the support registry; the other pinned files are the rest of the
#: loader-face input closure the generation tooling measured.
ARTIFACT_FILE = "tokenizer.json"


def certified_records() -> dict[str, dict[str, Any]]:
    """Family to registry record, one certified record per family."""
    document = load_json(REGISTRY_PATH)
    records = document.get("artifacts")
    if not isinstance(records, list) or not records:
        raise GenerationError(f"{REGISTRY_PATH} carries no artifact records")
    certified: dict[str, dict[str, Any]] = {}
    for record in records:
        if not isinstance(record, dict):
            raise GenerationError(f"{REGISTRY_PATH}: artifact records must be tables")
        family = str(record["family"])
        previous = certified.setdefault(family, record)
        if str(previous["artifact_sha256"]) != str(record["artifact_sha256"]):
            raise GenerationError(
                f"{family}: the support registry records two artifact digests "
                f"({previous['artifact_sha256']} and {record['artifact_sha256']})"
            )
    return certified


def certified_artifacts() -> dict[str, str]:
    """Family to certified artifact digest, from the shipped registry."""
    return {
        family: str(record["artifact_sha256"])
        for family, record in certified_records().items()
    }


def check_shipped(path: Path) -> list[str]:
    """Check the shipped file on its own terms.

    Checked here: the file is in the deterministic serialised form, the
    library's own manifest reader accepts it (no second copy of the
    parsing rules lives in this tool), its contents agree with the
    support registry that ships next to it, every record that declares
    configuration-side added tokens has its source file pinned, and a
    converted family pins exactly its conversion output.
    """
    if not path.exists():
        return [f"{path}: file is missing"]
    raw = path.read_bytes()
    if str(SOURCE_ROOT) not in sys.path:
        sys.path.insert(0, str(SOURCE_ROOT))
    from toktier.artifacts import ArtifactManifest
    from toktier.artifacts.conversion import CONVERSIONS
    from toktier.errors import RegistryInvalid

    try:
        manifest = ArtifactManifest.load(path)
    except RegistryInvalid as error:
        return [f"{path}: the library rejects this manifest: {error}"]

    problems: list[str] = []
    document = {
        family: {
            "repo_id": entry.repo_id,
            "revision": entry.revision,
            "files": {
                item.name: {"sha256": item.sha256, "size": item.size}
                for item in entry.files
            },
        }
        for family, entry in sorted(manifest.entries.items())
    }
    if serialise_document(document) != raw:
        problems.append(
            f"{path}: file is not in the deterministic serialised form "
            "(regenerate with the tool rather than editing by hand)"
        )
    records = certified_records()
    certified = {
        family: str(record["artifact_sha256"])
        for family, record in records.items()
    }
    shipped = set(manifest.families())
    if shipped != set(certified):
        problems.append(
            f"{path}: families differ from {REGISTRY_PATH.name}: "
            f"only in the manifest {sorted(shipped - set(certified))}, "
            f"only in the registry {sorted(set(certified) - shipped)}"
        )
    for family in sorted(shipped & set(certified)):
        files = manifest.get(family).files
        names = [item.name for item in files]
        if ARTIFACT_FILE not in names:
            problems.append(
                f"{path}: {family} pins {names}, which does not include "
                f"{ARTIFACT_FILE}"
            )
            continue
        if family in CONVERSIONS and names != [ARTIFACT_FILE]:
            # A converted family's cache holds exactly the conversion
            # output; pinning more would name files no source serves.
            problems.append(
                f"{path}: {family} is converted locally, so its entry pins "
                f"[{ARTIFACT_FILE}] alone; it pins {names}"
            )
        for item in files:
            if item.name == ARTIFACT_FILE and item.sha256 != certified[family]:
                problems.append(
                    f"{path}: {family} pins {item.sha256} for {ARTIFACT_FILE} "
                    f"but the support registry certifies {certified[family]}"
                )
            if item.size is None:
                problems.append(
                    f"{path}: {family}/{item.name} does not record a byte length"
                )
        claim = records[family].get("config_added_tokens")
        source = claim.get("source") if isinstance(claim, dict) else None
        if isinstance(source, str) and source not in names:
            problems.append(
                f"{path}: {family} declares configuration-side added tokens "
                f"from {source} but the manifest does not pin that file; a "
                "cold cache built from this manifest could not rebuild the "
                "certified loader face"
            )
    return problems


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Check the shipped artifact manifest."
    )
    parser.add_argument("--out", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify the shipped file.",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    arguments = build_parser().parse_args(argv)
    if not arguments.check:
        raise GenerationError(
            "this tool verifies the shipped manifest (--check); the "
            "manifest itself is generated by the maintainers from the "
            "frozen artifact files"
        )
    problems = check_shipped(arguments.out)
    for problem in problems:
        print(f"error: {problem}", file=sys.stderr)
    if problems:
        return 1
    print(f"{arguments.out}: check passed")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except GenerationError as error:  # pragma: no cover - command line surface
        print(f"error: {error}", file=sys.stderr)
        raise SystemExit(2) from error
