#!/usr/bin/env python3
"""Apply the checked corrected-Gigatoken binding to the support registry.

The campaign registry is generated by maintainer tooling that is intentionally
not shipped.  This small, deterministic augmentation tool owns only the
``fast_cpu`` backend entries.  It refuses any mismatch between the binding,
the packaged repair table, and the artifact roster before it writes both the
repository and wheel copies with a recomputed registry root digest.
"""

from __future__ import annotations

import argparse
import copy
import hashlib
import sys
import zlib
from pathlib import Path
from typing import Any

from registry_common import (
    REGISTRY_DOMAIN_TAG,
    GenerationError,
    load_json,
    schema_violations,
    serialise_document,
    sha256_of_file,
    with_root_digest,
)

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_REGISTRY = REPOSITORY_ROOT / "tables" / "support_registry.json"
PACKAGED_REGISTRY = (
    REPOSITORY_ROOT
    / "src"
    / "toktier"
    / "routing"
    / "tables"
    / "support_registry.v1.json"
)
BINDING_PATH = REPOSITORY_ROOT / "tools" / "fast_cpu_binding.json"
REPAIR_TABLE_PATH = (
    REPOSITORY_ROOT
    / "src"
    / "toktier"
    / "repair"
    / "tables"
    / "fast_repair_families.v1.json"
)
REPAIR_PCLASS_PATH = REPAIR_TABLE_PATH.with_name("repair_pclass.v1.zlib")
PATCH_PATH = (
    REPOSITORY_ROOT
    / "packaging"
    / "fast_cpu"
    / "gigatoken-toktier-pinned-1.patch"
)
LICENSE_PATH = REPOSITORY_ROOT / "packaging" / "fast_cpu" / "LICENSE-gigatoken"
NOTICE_PATH = (
    REPOSITORY_ROOT / "packaging" / "fast_cpu" / "NOTICE-gigatoken-pinned"
)
FOCUSED_PARITY_PATH = REPOSITORY_ROOT / "readings" / "fast_cpu_focused_parity.json"
SCHEMA_PATH = REPOSITORY_ROOT / "schemas" / "support_registry.schema.json"
VENDOR_DIR = REPOSITORY_ROOT / "src" / "toktier" / "_vendor"
VENDOR_MANIFEST_PATH = VENDOR_DIR / "gigatoken_build.json"


def _require_mapping(value: object, *, label: str) -> dict[str, Any]:
    if not isinstance(value, dict):
        raise GenerationError(f"{label} must be a JSON object")
    return value


def augmented_document(
    registry: dict[str, Any], binding: dict[str, Any]
) -> dict[str, Any]:
    """Return ``registry`` with exactly the binding-owned entries applied."""
    if binding.get("version") != "fast-cpu-binding-v1":
        raise GenerationError("unknown fast CPU binding version")
    if binding.get("backend") != "fast_cpu":
        raise GenerationError("fast CPU binding names the wrong backend")
    if binding.get("repair_config_id") != "toktier-fast-repair-v1":
        raise GenerationError("fast CPU binding names the wrong repair config")
    if (
        binding.get("engine_distribution") != "toktier"
        or binding.get("engine_module") != "toktier._vendor.gigatoken_rs"
        or binding.get("engine_delivery") != "vendored"
    ):
        raise GenerationError("fast CPU binding names the wrong delivery identity")

    loadable = set(binding.get("loadable_families") or ())
    rejected_raw = _require_mapping(
        binding.get("rejected_families"), label="rejected_families"
    )
    rejected = set(rejected_raw)
    if len(loadable) != 11:
        raise GenerationError(
            f"fast CPU binding must certify 11 unique artifacts, found {len(loadable)}"
        )
    if loadable & rejected:
        raise GenerationError("a family is both loadable and rejected")

    for field in (
        "engine_wheel_sha256",
        "campaign_wheel_sha256",
        "binary_digest",
        "patch_sha256",
    ):
        value = binding.get(field)
        if not isinstance(value, str) or len(value) != 64 or any(
            character not in "0123456789abcdef" for character in value
        ):
            raise GenerationError(f"{field} must be a lowercase SHA-256 digest")
    equivalence = _require_mapping(
        binding.get("native_equivalence"), label="native_equivalence"
    )
    if (
        equivalence.get("campaign_binary_digest") != binding["binary_digest"]
        or equivalence.get("release_binary_digest") != binding["binary_digest"]
    ):
        raise GenerationError(
            "campaign and release wheels must bind the same certified native module"
        )

    coverage = _require_mapping(binding.get("coverage"), label="coverage")
    if coverage.get("unique_tokenizer_artifacts") != len(loadable):
        raise GenerationError("fast CPU coverage must count 11 unique artifacts")
    if coverage.get("model_families") != 12:
        raise GenerationError("fast CPU coverage must count 12 model families")
    inheritance = _require_mapping(
        coverage.get("exact_artifact_inheritance"),
        label="coverage.exact_artifact_inheritance",
    )
    if (
        inheritance.get("inherits_from") != "qwen3_8b"
        or inheritance.get("artifact_sha256")
        != "aeb13307a71acd8fe81861d94ad54ab689df773318809eed3cbe794b4492dae4"
        or inheritance.get("basis") != "tokenizer.json bytes are identical"
    ):
        raise GenerationError("the Nemotron-Terminal inheritance record drifted")
    inherited_repositories = inheritance.get("repositories")
    if not isinstance(inherited_repositories, list) or len(inherited_repositories) != 3:
        raise GenerationError(
            "the exact-artifact inheritance must name three repositories"
        )

    if sha256_of_file(PATCH_PATH) != binding.get("patch_sha256"):
        raise GenerationError("the shipped Gigatoken patch digest does not match")
    if not LICENSE_PATH.is_file() or not NOTICE_PATH.is_file():
        raise GenerationError("the Gigatoken license or modification notice is missing")

    vendor_manifest = _require_mapping(
        load_json(VENDOR_MANIFEST_PATH), label="vendored Gigatoken manifest"
    )
    expected_manifest = {
        "schema": "toktier.vendored_gigatoken.v1",
        "engine": binding["engine"],
        "engine_version": binding["engine_version"],
        "delivery": binding["engine_delivery"],
        "module": binding["engine_module"],
        "native_sha256": binding["binary_digest"],
        "source_wheel_sha256": binding["engine_wheel_sha256"],
        "patch_sha256": binding["patch_sha256"],
        "sbom_sha256": binding["vendored_sbom_sha256"],
        "sbom_repository_path": binding["vendored_sbom_path"],
        "sbom_distribution_path": binding["vendored_sbom_distribution_path"],
        "license_bundle_repository_path": binding[
            "vendored_license_bundle_path"
        ],
        "license_bundle_sha256": binding["vendored_license_bundle_sha256"],
    }
    for field, expected in expected_manifest.items():
        if vendor_manifest.get(field) != expected:
            raise GenerationError(
                f"vendored Gigatoken manifest field {field!r} does not match"
            )
    native_path = REPOSITORY_ROOT / str(binding["vendored_native_path"])
    if (
        native_path.parent != VENDOR_DIR
        or native_path.name != vendor_manifest.get("native_file")
        or sha256_of_file(native_path) != vendor_manifest.get("native_sha256")
    ):
        raise GenerationError("vendored_native_path does not match the manifest")
    sbom_path = REPOSITORY_ROOT / str(binding["vendored_sbom_path"])
    if (
        sbom_path.parent != REPOSITORY_ROOT / "packaging" / "fast_cpu"
        or str(binding["vendored_sbom_path"])
        != vendor_manifest.get("sbom_repository_path")
        or sha256_of_file(sbom_path) != vendor_manifest.get("sbom_sha256")
    ):
        raise GenerationError("vendored_sbom_path does not match the manifest")
    license_bundle = REPOSITORY_ROOT / str(binding["vendored_license_bundle_path"])
    if sha256_of_file(license_bundle) != binding["vendored_license_bundle_sha256"]:
        raise GenerationError("vendored Gigatoken license bundle digest does not match")

    repair = _require_mapping(
        load_json(REPAIR_TABLE_PATH), label="fast repair table"
    )
    if repair.get("config_id") != binding.get("repair_config_id"):
        raise GenerationError("the packaged repair table uses another config id")
    repair_rows = repair.get("families")
    if not isinstance(repair_rows, list):
        raise GenerationError("the packaged repair table has no family rows")
    repair_by_family = {
        str(row.get("family")): row
        for row in repair_rows
        if isinstance(row, dict)
    }
    if set(repair_by_family) != loadable:
        raise GenerationError(
            "the packaged repair roster differs from the certified loadable roster"
        )
    pclass = _require_mapping(repair.get("pclass"), label="pclass metadata")
    compressed = REPAIR_PCLASS_PATH.read_bytes()
    if hashlib.sha256(compressed).hexdigest() != pclass.get("compressed_sha256"):
        raise GenerationError("the packaged pclass archive digest does not match")
    try:
        raw_pclass = zlib.decompress(compressed)
    except zlib.error as error:
        raise GenerationError("the packaged pclass archive is corrupt") from error
    if (
        len(raw_pclass) != 0x110000
        or hashlib.sha256(raw_pclass).hexdigest() != pclass.get("raw_sha256")
    ):
        raise GenerationError("the packaged pclass payload does not match")

    completed = copy.deepcopy(registry)
    artifacts = completed.get("artifacts")
    if not isinstance(artifacts, list):
        raise GenerationError("support registry carries no artifacts list")
    registry_families = {
        str(row.get("family"))
        for row in artifacts
        if isinstance(row, dict)
    }
    missing = loadable - registry_families
    if missing:
        raise GenerationError(
            "certified fast CPU families are absent from the support registry: "
            + ", ".join(sorted(missing))
        )
    registry_by_family = {
        str(row.get("family")): row
        for row in artifacts
        if isinstance(row, dict)
    }

    validation = _require_mapping(binding.get("validation"), label="validation")
    if validation.get("focused_public_api_parity") != (
        "readings/fast_cpu_focused_parity.json"
    ):
        raise GenerationError("the focused public-API parity reading is not bound")
    focused = _require_mapping(
        load_json(FOCUSED_PARITY_PATH), label="focused public-API parity reading"
    )
    if (
        focused.get("schema") != "toktier.fast_cpu.focused_parity.v2"
        or focused.get("unique_artifacts") != len(loadable)
        or focused.get("model_families") != 12
        or focused.get("all_ids_equal_hf") is not True
        or focused.get("all_executed_gigatoken_repair") is not True
    ):
        raise GenerationError("the focused public-API parity verdict is incomplete")
    focused_oracle = _require_mapping(focused.get("oracle"), label="focused.oracle")
    focused_engine = _require_mapping(focused.get("engine"), label="focused.engine")
    focused_release = _require_mapping(
        focused.get("release"), label="focused.release"
    )
    oracle_binding = _require_mapping(binding.get("oracle"), label="oracle")
    if (
        focused_oracle.get("package") != "tokenizers"
        or focused_oracle.get("version") != oracle_binding.get("tokenizers")
        or focused_engine.get("upstream_project") != binding.get("engine")
        or focused_engine.get("version") != binding.get("engine_version")
        or focused_engine.get("delivery") != binding.get("engine_delivery")
        or focused_engine.get("module") != binding.get("engine_module")
        or focused_engine.get("native_sha256") != binding.get("binary_digest")
        or focused_release.get("distribution") != "toktier"
        or focused_release.get("version") != "0.1.0"
        or focused_release.get("external_gigatoken_distribution_present") is not False
        or not isinstance(focused_release.get("wheel_sha256"), str)
        or len(str(focused_release.get("wheel_sha256"))) != 64
    ):
        raise GenerationError("the focused parity engine/oracle binding drifted")
    focused_rows = focused.get("rows")
    if not isinstance(focused_rows, list):
        raise GenerationError("the focused public-API parity reading has no rows")
    focused_by_family = {
        str(row.get("family")): row
        for row in focused_rows
        if isinstance(row, dict)
    }
    if set(focused_by_family) != loadable:
        raise GenerationError("the focused parity roster differs from the binding")
    for family, focused_row in focused_by_family.items():
        path_counts = focused_row.get("path_counts")
        if (
            focused_row.get("artifact_sha256")
            != registry_by_family[family].get("artifact_sha256")
            or focused_row.get("plan_backend") != "fast_cpu"
            or focused_row.get("all_turns_equal_hf") is not True
            or not isinstance(path_counts, dict)
            or int(path_counts.get("gigatoken_repair", 0)) < 1
        ):
            raise GenerationError(f"{family}: focused public-API parity did not pass")
    for family, repair_row in repair_by_family.items():
        artifact_sha = registry_by_family[family].get("artifact_sha256")
        if repair_row.get("artifact_sha256") != artifact_sha:
            raise GenerationError(
                f"{family}: repair table and registry artifact digests differ"
            )
    known_rejected = rejected & registry_families
    if registry_families != loadable | known_rejected:
        unexpected = registry_families - loadable - known_rejected
        raise GenerationError(
            "every shipped artifact must be classified by the fast CPU binding; "
            f"unclassified: {', '.join(sorted(unexpected))}"
        )

    config_digest = sha256_of_file(REPAIR_TABLE_PATH)
    certified_entry = {
        "status": "certified",
        "binary_digest": str(binding["binary_digest"]),
        "engine": str(binding["engine"]),
        "engine_version": str(binding["engine_version"]),
        "engine_delivery": str(binding["engine_delivery"]),
        "engine_module": str(binding["engine_module"]),
        "engine_unicode_data": str(binding["engine_unicode_data"]),
        "patch_sha256": str(binding["patch_sha256"]),
        "config_id": str(binding["repair_config_id"]),
        "config_digest": config_digest,
    }
    for row in artifacts:
        if not isinstance(row, dict):
            raise GenerationError("support registry has a non-object artifact row")
        family = str(row.get("family"))
        backends = row.get("backends")
        if not isinstance(backends, dict):
            raise GenerationError(f"{family}: backends must be an object")
        if family in loadable:
            backends["fast_cpu"] = dict(certified_entry)
        elif family in known_rejected:
            backends["fast_cpu"] = {
                "status": "unsupported",
                "engine": str(binding["engine"]),
                "engine_version": str(binding["engine_version"]),
                "engine_delivery": str(binding["engine_delivery"]),
                "engine_module": str(binding["engine_module"]),
                "config_id": str(binding["repair_config_id"]),
                "config_digest": config_digest,
            }

    return with_root_digest(completed, REGISTRY_DOMAIN_TAG)


def _write(path: Path, document: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(serialise_document(document))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Apply or check the shipped fast CPU registry binding."
    )
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args(argv)

    registry = _require_mapping(load_json(DEFAULT_REGISTRY), label="registry")
    binding = _require_mapping(load_json(BINDING_PATH), label="binding")
    generated = augmented_document(registry, binding)
    violations = schema_violations(generated, load_json(SCHEMA_PATH))
    if violations:
        raise GenerationError(
            "augmented registry violates its schema:\n  " + "\n  ".join(violations)
        )
    payload = serialise_document(generated)
    if arguments.check:
        problems = []
        for path in (DEFAULT_REGISTRY, PACKAGED_REGISTRY):
            if not path.is_file() or path.read_bytes() != payload:
                problems.append(f"{path} is not the generated fast CPU registry")
        for problem in problems:
            print(f"error: {problem}", file=sys.stderr)
        return 1 if problems else 0
    _write(DEFAULT_REGISTRY, generated)
    _write(PACKAGED_REGISTRY, generated)
    print(f"updated {DEFAULT_REGISTRY} and {PACKAGED_REGISTRY}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except GenerationError as error:
        print(f"error: {error}", file=sys.stderr)
        raise SystemExit(2) from error
